import { useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import { PageHead } from './kit'

type SetupStep = 'department' | 'program' | 'course' | 'student'

const stepCopy: Record<SetupStep, { number: string, eyebrow: string, title: string, description: string }> = {
  department: { number: '01', eyebrow: 'Foundation', title: 'Add a department', description: 'Start with the academic unit that owns programs and courses.' },
  program: { number: '02', eyebrow: 'Structure', title: 'Add a program', description: 'Attach the program to a department in this branch.' },
  course: { number: '03', eyebrow: 'Curriculum', title: 'Create a course', description: 'Build the tenant-local curriculum before offering a section.' },
  student: { number: '04', eyebrow: 'People', title: 'Create a student', description: 'Register the first student against this branch’s catalog.' },
}

export default function AcademicCatalog() {
  const [departments, setDepartments] = useState<any[]>([]), [programs, setPrograms] = useState<any[]>([])
  const [department, setDepartment] = useState({ code: '', name: '' })
  const [program, setProgram] = useState({ code: '', name: '', dept_id: '', level: 'UG', duration_years: 4 })
  const [course, setCourse] = useState({ code: '', title: '', dept_code: '', program_id: '', credits: 3, semester: 1 })
  const [student, setStudent] = useState({ name: '', roll_no: '', dept_code: '', program_id: '', batch: '2026', semester: 1 })
  const [activeStep, setActiveStep] = useState<SetupStep>('department')
  const [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false)

  const load = () => Promise.all([api.departments(), api.programs()]).then(([d, p]) => {
    setDepartments(d.departments); setPrograms(p.programs)
    if (d.departments[0]) {
      setProgram(x => x.dept_id ? x : ({ ...x, dept_id: d.departments[0].id }))
      setCourse(x => x.dept_code ? x : ({ ...x, dept_code: d.departments[0].code }))
      setStudent(x => x.dept_code ? x : ({ ...x, dept_code: d.departments[0].code }))
    }
  }).catch((e: any) => setError(e.message))

  useEffect(() => { load() }, [])
  const selectedCourseDepartment = useMemo(() => departments.find(row => row.code === course.dept_code), [departments, course.dept_code])
  const programsForCourse = useMemo(() => selectedCourseDepartment ? programs.filter(row => row.dept_id === selectedCourseDepartment.id) : [], [programs, selectedCourseDepartment])
  const programsForStudent = useMemo(() => programs.filter(p => departments.find(d => d.id === p.dept_id)?.code === student.dept_code), [programs, departments, student.dept_code])
  const hasCatalogFoundation = Boolean(departments.length && programs.length)
  const studentReady = Boolean(student.name.trim() && student.dept_code && student.program_id && programsForStudent.some(row => row.id === student.program_id) && student.batch.trim() && student.semester >= 1 && student.semester <= 8)

  async function addDepartment() { setBusy(true); setError(''); try { await api.createDepartment(department); setDepartment({ code: '', name: '' }); await load(); setActiveStep('program') } catch (e: any) { setError(e.message) } setBusy(false) }
  async function addProgram() { setBusy(true); setError(''); try { await api.createProgram(program); setProgram(x => ({ ...x, code: '', name: '' })); await load(); setActiveStep('course') } catch (e: any) { setError(e.message) } setBusy(false) }
  async function addCourse() { setBusy(true); setError(''); try { await api.createCourse(course); setCourse(x => ({ ...x, code: '', title: '' })); await load(); setActiveStep('student') } catch (e: any) { setError(e.message) } setBusy(false) }
  async function addStudent() { if (!studentReady) { setError('Complete every required student field and select a program for the selected department.'); return } setBusy(true); setError(''); setMessage(''); try { const created = await api.addStudent(student); setStudent(x => ({ ...x, name: '', roll_no: '' })); setMessage(`Student ${created.roll_no} created successfully.`); await load() } catch (e: any) { setError(e.message) } setBusy(false) }
  async function remove(kind: 'department' | 'program', id: string) { if (!window.confirm(`Delete this ${kind}?`)) return; try { kind === 'department' ? await api.deleteDepartment(id) : await api.deleteProgram(id); await load() } catch (e: any) { setError(e.message) } }
  async function editDepartment(row: any) { const code = window.prompt('Department code', row.code); const name = window.prompt('Department name', row.name); if (!code || !name) return; try { await api.updateDepartment(row.id, { code, name }); await load() } catch (e: any) { setError(e.message) } }
  async function editProgram(row: any) { const code = window.prompt('Program code', row.code); const name = window.prompt('Program name', row.name); if (!code || !name) return; try { await api.updateProgram(row.id, { code, name, dept_id: row.dept_id, level: row.level, duration_years: row.duration_years }); await load() } catch (e: any) { setError(e.message) } }

  const stepForm = () => {
    if (activeStep === 'department') return <div className="academic-form-grid"><label><span>Department code</span><input className="inp" placeholder="e.g. CSE" value={department.code} onChange={e => setDepartment({ ...department, code: e.target.value })} /></label><label><span>Department name</span><input className="inp" placeholder="e.g. Computer Science" value={department.name} onChange={e => setDepartment({ ...department, name: e.target.value })} /></label><button className="btn btn-crimson academic-submit" disabled={busy || !department.code || !department.name} onClick={addDepartment}>{busy ? 'Saving...' : 'Add Department'}</button></div>
    if (activeStep === 'program') return <div className="academic-form-grid"><label><span>Program code</span><input className="inp" placeholder="e.g. BTECH-CSE" value={program.code} onChange={e => setProgram({ ...program, code: e.target.value })} /></label><label><span>Program name</span><input className="inp" placeholder="e.g. B.Tech Computer Science" value={program.name} onChange={e => setProgram({ ...program, name: e.target.value })} /></label><label className="academic-form-wide"><span>Owning department</span><select className="select" value={program.dept_id} onChange={e => setProgram({ ...program, dept_id: e.target.value })}><option value="">Select department</option>{departments.map(row => <option key={row.id} value={row.id}>{row.code} — {row.name}</option>)}</select></label><button className="btn btn-crimson academic-submit" disabled={busy || !departments.length || !program.code || !program.name || !program.dept_id} onClick={addProgram}>{busy ? 'Saving...' : 'Add Program'}</button></div>
    if (activeStep === 'course') return <div className="academic-form-grid"><label><span>Course code</span><input className="inp" placeholder="e.g. CSE101" value={course.code} onChange={e => setCourse({ ...course, code: e.target.value })} /></label><label><span>Course title</span><input className="inp" placeholder="e.g. Programming Foundations" value={course.title} onChange={e => setCourse({ ...course, title: e.target.value })} /></label><label><span>Department</span><select className="select" value={course.dept_code} onChange={e => setCourse({ ...course, dept_code: e.target.value, program_id: '' })}><option value="">Select department</option>{departments.map(row => <option key={row.id} value={row.code}>{row.code} — {row.name}</option>)}</select></label><label><span>Program <em>optional</em></span><select className="select" value={course.program_id} onChange={e => setCourse({ ...course, program_id: e.target.value })}><option value="">{!course.dept_code ? 'Select a department first' : programsForCourse.length ? 'Select program' : 'No programs available for this department'}</option>{programsForCourse.map(row => <option key={row.id} value={row.id}>{row.code} — {row.name}</option>)}</select></label><label><span>Semester</span><input className="inp" type="number" min="1" max="8" value={course.semester} onChange={e => setCourse({ ...course, semester: Number(e.target.value) })} /></label><label><span>Credits</span><input className="inp" type="number" min="1" value={course.credits} onChange={e => setCourse({ ...course, credits: Number(e.target.value) })} /></label><button className="btn btn-crimson academic-submit" disabled={busy || !departments.length || !course.code || !course.title || !course.dept_code} onClick={addCourse}>{busy ? 'Saving...' : 'Create Course'}</button></div>
    return <div className="academic-form-grid"><label><span>Student name</span><input className="inp" placeholder="Full name" value={student.name} onChange={e => setStudent({ ...student, name: e.target.value })} /></label><label><span>Roll number <em>optional</em></span><input className="inp" placeholder="e.g. 2026-CSE-001" value={student.roll_no} onChange={e => setStudent({ ...student, roll_no: e.target.value })} /></label><label><span>Department</span><select className="select" value={student.dept_code} onChange={e => setStudent({ ...student, dept_code: e.target.value, program_id: '' })}><option value="">Select department</option>{departments.map(row => <option key={row.id} value={row.code}>{row.code} — {row.name}</option>)}</select></label><label><span>Program <em>required</em></span><select className="select" value={student.program_id} onChange={e => setStudent({ ...student, program_id: e.target.value })}><option value="">Select program for this department</option>{programsForStudent.map(row => <option key={row.id} value={row.id}>{row.code} — {row.name}</option>)}</select></label><label><span>Semester</span><input className="inp" type="number" min="1" max="8" value={student.semester} onChange={e => setStudent({ ...student, semester: Number(e.target.value) })} /></label><label><span>Batch</span><input className="inp" placeholder="e.g. 2026" value={student.batch} onChange={e => setStudent({ ...student, batch: e.target.value })} /></label><button className="btn btn-crimson academic-submit" title={studentReady ? 'Create student' : 'Complete the required fields and select a program for this department'} disabled={busy || !studentReady} onClick={addStudent}>{busy ? 'Saving...' : 'Create Student'}</button></div>
  }

  return <div className="fade-in principal-operations academic-setup-page">
    <PageHead title="Academic Setup" sub="Build a branch-owned academic catalog. Nothing on this page reuses Main Campus records." />
    {error && <p className="err-box">{error}</p>}
    {message && <p className="success-box">{message}</p>}
    <section className="academic-setup-hero"><div><span>Principal workspace · branch-local catalog</span><h2>Set up your academic foundation with clarity.</h2><p>Create the building blocks in order, then move to Academics to offer sections and run daily operations.</p></div><div className="academic-hero-status"><b>{hasCatalogFoundation ? 'Catalog ready' : 'Setup in progress'}</b><small>{departments.length} departments · {programs.length} programs</small></div></section>
    <section className="academic-setup-steps" aria-label="Academic setup progress">{(Object.keys(stepCopy) as SetupStep[]).map(step => <button type="button" key={step} className={activeStep === step ? 'active' : ''} onClick={() => setActiveStep(step)}><i>{stepCopy[step].number}</i><span><b>{stepCopy[step].title}</b><small>{step === 'department' ? `${departments.length} created` : step === 'program' ? `${programs.length} created` : step === 'course' ? 'Curriculum' : 'People'}</small></span></button>)}</section>
    <div className="academic-setup-layout"><aside className="academic-inventory"><div className="academic-inventory-head"><span>Catalog inventory</span><h3>Your branch structure</h3><p>Edit or remove entries here. Changes stay within this tenant.</p></div><section className="academic-inventory-section"><div><b>Departments</b><small>{departments.length} total</small></div>{departments.length ? departments.map(row => <article key={row.id}><span><b>{row.code}</b><small>{row.name}</small></span><em><button type="button" onClick={() => editDepartment(row)}>Edit</button><button type="button" onClick={() => remove('department', row.id)}>Delete</button></em></article>) : <p className="academic-empty">No departments yet.</p>}</section><section className="academic-inventory-section"><div><b>Programs</b><small>{programs.length} total</small></div>{programs.length ? programs.map(row => <article key={row.id}><span><b>{row.code}</b><small>{row.name}</small></span><em><button type="button" onClick={() => editProgram(row)}>Edit</button><button type="button" onClick={() => remove('program', row.id)}>Delete</button></em></article>) : <p className="academic-empty">Programs appear after a department is created.</p>}</section></aside><main className="academic-composer"><div className="academic-composer-head"><div><span>{stepCopy[activeStep].eyebrow} · Step {stepCopy[activeStep].number}</span><h3>{stepCopy[activeStep].title}</h3><p>{stepCopy[activeStep].description}</p></div><b>{activeStep === 'course' ? 'Sections next in Academics' : activeStep === 'student' ? 'Assigned to this branch campus' : 'Tenant-local record'}</b></div>{stepForm()}</main></div>
    <section className="academic-next"><div><span>What happens next</span><h3>From catalog to daily academic operations</h3></div><div><b>1</b><p>Set up departments and programs here.</p></div><div><b>2</b><p>Create courses, then offer sections from Academics.</p></div><div><b>3</b><p>Enroll students using your own branch catalog.</p></div></section>
  </div>
}
