import { useEffect, useState } from 'react'
import { api } from '../api'
import { Empty, PageHead, Spinner, money } from './kit'

const stateLabel = (state: string) => ({ draft: 'Coordinator preparation', 'HOD Review': 'Awaiting HOD review', 'Dean Review': 'Awaiting Dean review', 'Principal Review': 'Exception awaiting Principal', 'Finance Review': 'Awaiting Finance check', 'Ready to Execute': 'Ready for Coordinator execution', completed: 'Completed' }[state] || state)

export default function AcademicRollover() {
  const [data, setData] = useState<any>(null), [error, setError] = useState(''), [reason, setReason] = useState(''), [drafts, setDrafts] = useState<Record<string, any>>({})
  const [form, setForm] = useState({ source_academic_year: '', source_semester: 1, target_academic_year: '', target_semester: 2 })
  const load = async () => { setError(''); try { setData(await api.academicRollovers()) } catch (e: any) { setError(e.message) } }
  useEffect(() => { load() }, [])
  if (!data) return <Spinner />
  // Keep the latest completed record visible as an execution receipt, while
  // allowing a Coordinator to start the next distinct term once no review is
  // active.  Previously completed records disappeared for Coordinators and
  // inadvertently blocked the next cycle.
  const open = data.rollovers?.find((item: any) => item.status !== 'completed')
  const current = open || data.rollovers?.[0] || null
  const canStart = data.can_create && !open
  const fail = (e: any) => setError(e.message || 'The workflow action could not be completed.')
  const start = async () => { try { await api.startAcademicRollover(form); setReason(''); load() } catch (e: any) { fail(e) } }
  const decide = async (student_id: string, decision: string, note = '') => { try { await api.decideAcademicRollover(current.id, { student_id, decision, note }); setDrafts(current => { const next = { ...current }; delete next[student_id]; return next }); load() } catch (e: any) { fail(e) } }
  const submit = async () => { try { await api.submitAcademicRollover(current.id, { version_no: current.version_no, reason }); setReason(''); load() } catch (e: any) { fail(e) } }
  const action = async (value: string) => { try { await api.actionAcademicRollover(current.id, value, { version_no: current.version_no, reason }); setReason(''); load() } catch (e: any) { fail(e) } }
  const execute = async () => { if (!confirm(`Execute version ${current.version_no} for ${current.summary?.eligible || 0} promoted student(s)? This creates immutable academic history.`)) return; try { await api.executeAcademicRollover(current.id, { version_no: current.version_no, reason }); setReason(''); load() } catch (e: any) { fail(e) } }
  const actionName = data.role === 'HOD' ? 'hod_approve' : data.role === 'Dean Academics' ? 'dean_approve' : data.role === 'Principal' ? 'principal_approve' : data.role === 'Finance Manager' ? 'finance_confirm' : ''
  const canApprove = current && ((data.role === 'HOD' && current.status === 'HOD Review') || (data.role === 'Dean Academics' && current.status === 'Dean Review') || (data.role === 'Principal' && current.status === 'Principal Review') || (data.role === 'Finance Manager' && current.status === 'Finance Review'))
  return <div className="fade-in">
    <PageHead title="Student Progression & Semester Rollover" sub="End-of-term student progression after results are published, with HOD, Dean, exception and Finance controls." />
    {error && <p className="hint" role="alert" style={{ color: 'var(--rose)' }}>{error}</p>}
    {canStart && <section className="card card-pad"><h3>Start an end-of-term progression review</h3><p className="hint">Use this only after final results are published for every active student in the closing semester. It does not create calendar events, offerings, or timetables; it records governed student progression.</p><div className="grid-2"><label>Closing academic year<input className="inp" required value={form.source_academic_year} onChange={e => setForm({ ...form, source_academic_year: e.target.value })} placeholder="2026-27" /></label><label>Closing semester<input className="inp" type="number" min="1" value={form.source_semester} onChange={e => setForm({ ...form, source_semester: Number(e.target.value) })} /></label><label>Next academic year<input className="inp" required value={form.target_academic_year} onChange={e => setForm({ ...form, target_academic_year: e.target.value })} placeholder="2027-28" /></label><label>Next semester<input className="inp" type="number" min="1" value={form.target_semester} onChange={e => setForm({ ...form, target_semester: Number(e.target.value) })} /></label></div><button className="btn btn-crimson" style={{ marginTop: 16 }} onClick={start}>Create progression review</button></section>}
    {current ? <section className="card"><div className="card-h"><div><h3>{current.source_academic_year} · Semester {current.source_semester} → {current.target_academic_year} · Semester {current.target_semester}</h3><span className="hint">Version {current.version_no} · {stateLabel(current.status)}</span>{current.status === 'completed' && <p className="hint">Execution completed. This is the permanent progression receipt; student decisions and academic history are now read-only.</p>}{current.workflow_reason && <p className="hint">{current.workflow_reason}</p>}</div><span className="pill">{stateLabel(current.status)}</span></div><div className="kpi-row" style={{ padding: 18 }}><div className="kpi"><div className="kpi-v">{current.summary.total}</div><div className="kpi-l">Students reviewed</div></div><div className="kpi"><div className="kpi-v">{current.summary.eligible}</div><div className="kpi-l">Promoted</div></div><div className="kpi"><div className="kpi-v">{current.summary.exceptions}</div><div className="kpi-l">Exceptions</div></div><div className="kpi"><div className="kpi-v">{money(current.summary.outstanding)}</div><div className="kpi-l">Finance visibility</div></div></div>
      <div className="card-pad" style={{ paddingTop: 0 }}>{data.role === 'Coordinator' && current.status === 'draft' && <><p className="hint">Complete every decision, then submit this exact version to HOD. Enter the supporting reason before selecting an exception.</p><textarea className="inp" value={reason} onChange={e => setReason(e.target.value)} placeholder="Submission note or exception reason" /><button className="btn btn-crimson" style={{ marginTop: 10 }} onClick={submit}>Submit to HOD</button></>}{canApprove && <><label>Review note<textarea className="inp" value={reason} onChange={e => setReason(e.target.value)} placeholder="Required for return; retained in audit history" /></label><div className="row-actions" style={{ marginTop: 10 }}><button className="btn btn-crimson" onClick={() => action(actionName)}>{data.role === 'Finance Manager' ? 'Confirm finance check' : 'Approve and hand off'}</button><button className="btn btn-out" onClick={() => action('return')}>Return for correction</button></div></>}{data.role === 'Coordinator' && current.status === 'Ready to Execute' && <button className="btn btn-crimson" onClick={execute}>Execute approved rollover</button>}</div>
      <div className="tbl-scroll"><table className="tbl"><thead><tr><th>Roll No.</th><th>Student</th><th>Academic evidence</th><th>Finance</th><th>Outstanding</th><th>Progression decision</th></tr></thead><tbody>{current.decisions.map((item: any) => { const draft = drafts[item.student_id] || { decision: item.decision, note: item.note || '' }; const needsReason = draft.decision !== 'pending' && draft.decision !== 'promoted'; return <tr key={item.student_id}><td className="mono">{item.roll_no}</td><td>{item.name}</td><td>{item.academic_status}</td><td>{item.finance_status}</td><td>{money(item.outstanding_amount)}</td><td>{data.role === 'Coordinator' && current.status === 'draft' ? <div className="rollover-decision-cell"><select className="select" value={draft.decision} onChange={e => setDrafts(current => ({ ...current, [item.student_id]: { ...draft, decision: e.target.value } }))}><option value="pending">Select decision</option><option value="promoted">Promoted</option><option value="detained">Detained</option><option value="repeating">Repeating</option><option value="hold">Hold</option><option value="exception">Exception</option></select>{needsReason && <textarea className="inp" rows={2} value={draft.note} onChange={e => setDrafts(current => ({ ...current, [item.student_id]: { ...draft, note: e.target.value } }))} placeholder="Required rationale" />}{draft.decision !== 'pending' && <button className="btn btn-out" disabled={needsReason && draft.note.trim().length < 3} onClick={() => decide(item.student_id, draft.decision, draft.note)}>Save decision</button>}</div> : <>{item.decision}{item.note && <small className="rollover-decision-note">{item.note}</small>}</>}</td></tr>})}</tbody></table></div>
    </section> : !data.can_create && <Empty text="No scoped rollover is available for your role." />}
  </div>
}
