import { useEffect, useState } from 'react'
import { api } from '../api'
import { Empty, PageHead, Spinner, money } from './kit'

export default function AcademicRollover({ user }: { user: any }) {
  const [data, setData] = useState<any>(null)
  const [error, setError] = useState('')
  const [policy, setPolicy] = useState<any>(null)
  const [form, setForm] = useState({ source_academic_year: '', source_semester: 1, target_academic_year: '', target_semester: 2 })
  const load = () => { api.academicRollovers().then(setData).catch((e: any) => setError(e.message)); api.academicRolloverPolicy().then(setPolicy).catch(() => setPolicy(null)) }
  useEffect(() => { load() }, [])
  if (!data) return <Spinner />
  // Academic staff work on the open cycle; Finance/Principal can still view
  // the most recently approved cycle and its fee-publishing prompt.
  const current = data.rollovers?.find((item: any) => item.status !== 'approved') || (data.can_review ? null : data.rollovers?.[0])
  const update = async (student_id: string, decision: string) => { try { await api.decideAcademicRollover(current.id, { student_id, decision }); load() } catch (e: any) { setError(e.message) } }
  const start = async () => { try { await api.startAcademicRollover(form); load() } catch (e: any) { setError(e.message) } }
  const submit = async () => { try { await api.submitAcademicRollover(current.id); load() } catch (e: any) { setError(e.message) } }
  const approve = async () => { try { await api.approveAcademicRollover(current.id); load() } catch (e: any) { setError(e.message) } }
  const savePolicy = async () => { try { await api.updateAcademicRolloverPolicy(policy); load(); alert('Automatic progression policy saved.') } catch (e:any) { setError(e.message) } }
  const execute = async () => { if (!confirm(`Execute rollover for ${current.summary?.eligible || 0} promoted student(s)? Historical records will be preserved.`)) return; try { await api.executeAcademicRollover(current.id); load() } catch (e: any) { setError(e.message) } }
  return <div className="fade-in">
    <PageHead title="Academic Rollover" sub="Review each student before progression. Finance is prompted only after Principal approval." />
    {error && <p className="hint" style={{ color: 'var(--rose)' }}>{error}</p>}
    {policy && data.can_review && <section className="card card-pad" style={{marginBottom:16}}><h3>Automatic progression policy</h3><p className="hint">Applied automatically after all subject results are published for a student.</p><div className="grid-2"><label>Maximum allowed backlogs<input className="inp" type="number" min="0" max="20" value={policy.max_backlogs} onChange={e=>setPolicy({...policy,max_backlogs:Number(e.target.value)})}/></label><label>Minimum attendance (%)<input className="inp" type="number" min="0" max="100" value={policy.minimum_attendance_pct} onChange={e=>setPolicy({...policy,minimum_attendance_pct:Number(e.target.value)})}/></label><label>Fee dues policy<select className="select" value={policy.fee_policy} onChange={e=>setPolicy({...policy,fee_policy:e.target.value})}><option value="carry_forward">Promote with carry-forward</option><option value="block">Block promotion while dues exist</option></select></label></div><p className="hint">An active high-severity disciplinary case always places the student on hold. Attendance with no recorded data is not automatically blocked.</p><button className="btn btn-crimson" onClick={savePolicy}>Save policy</button></section>}
    {data.can_review && !current && <section className="card card-pad"><h3>Start semester rollover</h3><div className="grid-2"><label>Closing academic year<input className="inp" value={form.source_academic_year} onChange={e => setForm({ ...form, source_academic_year: e.target.value })} placeholder="2025-26" /></label><label>Closing semester<input className="inp" type="number" min="1" value={form.source_semester} onChange={e => setForm({ ...form, source_semester: Number(e.target.value) })} /></label><label>Next academic year<input className="inp" value={form.target_academic_year} onChange={e => setForm({ ...form, target_academic_year: e.target.value })} placeholder="2026-27" /></label><label>Next semester<input className="inp" type="number" min="1" value={form.target_semester} onChange={e => setForm({ ...form, target_semester: Number(e.target.value) })} /></label></div><button className="btn btn-crimson" style={{ marginTop: 16 }} onClick={start}>Create student review</button></section>}
    {current ? <section className="card"><div className="card-h"><div><h3>{current.source_academic_year} · Semester {current.source_semester} → {current.target_academic_year} · Semester {current.target_semester}</h3><span className="hint">Status: {current.status}</span></div>{data.can_review && current.status === 'draft' && <button className="btn btn-crimson" onClick={submit}>Submit for Principal approval</button>}{data.can_approve && current.status === 'awaiting_principal' && <button className="btn btn-crimson" onClick={approve}>Approve rollover</button>}{data.can_approve && current.status === 'approved' && <button className="btn btn-crimson" onClick={execute}>Execute rollover</button>}</div>{current.summary && <div className="kpi-row" style={{padding:18}}><div className="kpi"><div className="kpi-v">{current.summary.total}</div><div className="kpi-l">Students</div></div><div className="kpi"><div className="kpi-v">{current.summary.eligible}</div><div className="kpi-l">Promoted</div></div><div className="kpi"><div className="kpi-v">{money(current.summary.outstanding)}</div><div className="kpi-l">Outstanding dues</div></div></div>}<div className="tbl-scroll"><table className="tbl"><thead><tr><th>Roll No.</th><th>Student</th><th>Academic</th><th>Finance</th><th>Outstanding</th><th>Decision</th></tr></thead><tbody>{current.decisions.map((item: any) => <tr key={item.student_id}><td className="mono">{item.roll_no}</td><td>{item.name}</td><td>{item.academic_status}</td><td>{item.finance_status}</td><td>{money(item.outstanding_amount)}</td><td>{data.can_review && current.status === 'draft' ? <select className="select" value={item.decision} onChange={e => update(item.student_id, e.target.value)}><option value="pending">Select</option><option value="promoted">Promoted</option><option value="detained">Detained</option><option value="repeating">Repeating</option><option value="hold">Hold</option><option value="exception">Exception</option></select> : item.decision}</td></tr>)}</tbody></table></div></section> : !data.can_review && <Empty text="No rollover review is available yet." />}
  </div>
}
