import { useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import { DecisionToast, Modal, PageHead, Spinner } from './kit'

const blank = { code: '', title: '', dept_code: '', credits: 3, semester: 1, regulation: 'R2023', course_type: 'Core', category: 'Professional Core', ltp: '3-0-0', prerequisite: '', description: '' }

export default function CoursesSubjects() {
  const [data, setData] = useState<any>(null); const [query, setQuery] = useState(''); const [dept, setDept] = useState(''); const [sem, setSem] = useState(''); const [type, setType] = useState(''); const [status, setStatus] = useState(''); const [showAdd, setShowAdd] = useState(false); const [form, setForm] = useState<any>(blank); const [decision, setDecision] = useState<any>(null)
  const load = () => api.courses().then(setData).catch(() => setData({ courses: [], can_create: false }))
  useEffect(() => { load() }, [])
  const courses = data?.courses || []
  const departments = Array.from(new Set(courses.map((course: any) => course.dept))).filter(Boolean).sort() as string[]
  const filtered = useMemo(() => courses.filter((course: any) => (!dept || course.dept === dept) && (!sem || String(course.semester) === sem) && (!type || course.course_type === type) && (!status || course.status === status) && (!query || `${course.code} ${course.title}`.toLowerCase().includes(query.toLowerCase()))), [courses, dept, sem, type, status, query])
  const credits = filtered.reduce((sum: number, course: any) => sum + Number(course.credits || 0), 0)
  const byDept = departments.map(name => ({ name, count: filtered.filter((course: any) => course.dept === name).length })).filter(row => row.count)
  const maxDept = Math.max(1, ...byDept.map(row => row.count))
  function reset() { setQuery(''); setDept(''); setSem(''); setType(''); setStatus('') }
  async function submit() { try { const result = await api.createCourse(form); setDecision(result.decision); setShowAdd(false); setForm(blank); load() } catch (error: any) { setDecision({ outcome: 'DENY', reason: error.message }) } }
  if (!data) return <Spinner />
  return <div className="courses-page fade-in"><PageHead title="Courses & Subjects" sub="Master catalog of academic courses and subjects across departments" right={<div className="courses-actions">{data.can_create && <button className="btn btn-brass" onClick={() => { setForm({ ...blank, dept_code: departments[0] || '' }); setShowAdd(true) }}>+ Add Course</button>}<button className="btn btn-out" onClick={() => exportCsv(filtered)}>Export</button></div>} />
    <section className="courses-filters card"><label>Department<Select value={dept} set={setDept} options={departments} all="All Departments" /></label><label>Semester<Select value={sem} set={setSem} options={[...new Set(courses.map((course: any) => String(course.semester)))].sort()} all="All Semesters" /></label><label>Course Type<Select value={type} set={setType} options={[...new Set(courses.map((course: any) => course.course_type))]} all="All Types" /></label><label>Status<Select value={status} set={setStatus} options={[...new Set(courses.map((course: any) => course.status))]} all="All Statuses" /></label><label className="courses-search">Search<input className="inp" value={query} onChange={event => setQuery(event.target.value)} placeholder="Code or subject name" /></label><button className="btn btn-out" onClick={reset}>Reset</button></section>
    <section className="courses-stats"><Stat label="Total Courses" value={filtered.length} note="Across selected filters"/><Stat label="Active Subjects" value={filtered.filter((course: any) => course.status === 'Active').length} note="Currently active"/><Stat label="Core Courses" value={filtered.filter((course: any) => course.course_type === 'Core').length} note="Core curriculum"/><Stat label="Electives" value={filtered.filter((course: any) => course.course_type === 'Elective').length} note="Elective curriculum"/></section>
    <div className="courses-layout"><section className="courses-catalog card"><header><h2>Course & Subject Catalog <em>{filtered.length} records · {credits} credits</em></h2></header><div className="tbl-scroll"><table className="tbl"><thead><tr><th>Course code</th><th>Subject name</th><th>Department</th><th>Program</th><th>Type</th><th>Credits</th><th>Semester</th><th>Status</th></tr></thead><tbody>{filtered.map((course: any) => <tr key={course.id}><td><b className="mono">{course.code}</b></td><td><b>{course.title}</b><small>{course.category}</small></td><td>{course.dept}</td><td>{course.program}</td><td><span className={`course-pill ${course.course_type.toLowerCase()}`}>{course.course_type}</span></td><td>{course.credits}</td><td>Sem {course.semester}</td><td><span className="course-pill active">{course.status}</span></td></tr>)}</tbody></table></div>{!filtered.length && <p className="courses-none">No courses match the filters.</p>}</section><aside className="courses-side"><section className="card courses-panel"><h2>Distribution by Department</h2>{byDept.map(row => <div className="department-bar" key={row.name}><span>{row.name}</span><i><b style={{ width: `${row.count / maxDept * 100}%` }}/></i><em>{row.count}</em></div>)}</section><section className="card courses-panel"><h2>Catalog Summary</h2><p><b>{credits}</b> total credits in this view.</p><p><b>{new Set(filtered.map((course: any) => course.regulation)).size}</b> regulation version(s).</p><p><b>{new Set(filtered.map((course: any) => course.program)).size}</b> program(s) represented.</p></section></aside></div>
    {showAdd && <Modal title="Add Course" onClose={() => setShowAdd(false)} footer={<><button className="btn btn-out" onClick={() => setShowAdd(false)}>Cancel</button><button className="btn btn-brass" onClick={submit}>Create Course</button></>}><div className="grid-2"><Field label="Course code" value={form.code} set={(value: string) => setForm({ ...form, code: value })}/><Field label="Subject name" value={form.title} set={(value: string) => setForm({ ...form, title: value })}/><label>Department<select className="select" value={form.dept_code} onChange={event => setForm({ ...form, dept_code: event.target.value })}>{departments.map(item => <option key={item}>{item}</option>)}</select></label><Field label="Semester" type="number" value={form.semester} set={(value: string) => setForm({ ...form, semester: Number(value) })}/><Field label="Credits" type="number" value={form.credits} set={(value: string) => setForm({ ...form, credits: Number(value) })}/><label>Course Type<select className="select" value={form.course_type} onChange={event => setForm({ ...form, course_type: event.target.value })}><option>Core</option><option>Elective</option><option>Open Elective</option></select></label><Field label="Regulation" value={form.regulation} set={(value: string) => setForm({ ...form, regulation: value })}/><Field label="L-T-P" value={form.ltp} set={(value: string) => setForm({ ...form, ltp: value })}/><Field label="Category" value={form.category} set={(value: string) => setForm({ ...form, category: value })}/><Field label="Prerequisite" value={form.prerequisite} set={(value: string) => setForm({ ...form, prerequisite: value })}/></div></Modal>}{decision && <DecisionToast decision={decision} onClose={() => setDecision(null)}/>}</div>
}
function Select({ value, set, options, all }: any) { return <select className="select" value={value} onChange={event => set(event.target.value)}><option value="">{all}</option>{options.map((item: string) => <option key={item}>{item}</option>)}</select> }
function Field({ label, value, set, type = 'text' }: any) { return <label>{label}<input className="inp" type={type} value={value} onChange={event => set(event.target.value)}/></label> }
function Stat({ label, value, note }: any) { return <section className="courses-stat"><span>{label}</span><b>{value}</b><small>{note}</small></section> }
function exportCsv(rows: any[]) { const text = [['Code', 'Subject', 'Department', 'Program', 'Type', 'Credits', 'Semester', 'Status'], ...rows.map(row => [row.code, row.title, row.dept, row.program, row.course_type, row.credits, row.semester, row.status])].map(row => row.map(value => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([text], { type: 'text/csv' })); link.download = 'courses-subjects.csv'; link.click(); URL.revokeObjectURL(link.href) }
