import { useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import { Empty, Modal, PageHead, Spinner } from './kit'

export default function CoursesSubjects(){
 const [data,setData]=useState<any>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('ALL'),[selected,setSelected]=useState<any>(null)
 useEffect(()=>{api.courses().then(setData).catch(()=>setData({courses:[]}))},[])
 const courses=data?.courses||[]
 const filtered=useMemo(()=>courses.filter((x:any)=>`${x.code} ${x.title}`.toLowerCase().includes(query.toLowerCase())&&(filter==='ALL'||(filter==='UNASSIGNED'?x.unassigned_sections>0:filter==='OUTCOMES'?!x.outcome_count:filter==='PERFORMANCE'?x.pass_rate!=null&&x.pass_rate<60:filter==='PREREQUISITES'?x.prerequisite&&!courses.some((y:any)=>y.code===x.prerequisite):true))),[courses,query,filter])
 const count=(key:string)=>key==='UNASSIGNED'?courses.filter((x:any)=>x.unassigned_sections>0).length:key==='OUTCOMES'?courses.filter((x:any)=>!x.outcome_count).length:key==='PERFORMANCE'?courses.filter((x:any)=>x.pass_rate!=null&&x.pass_rate<60).length:courses.filter((x:any)=>x.prerequisite&&!courses.some((y:any)=>y.code===x.prerequisite)).length
 if(!data)return <Spinner/>
 return <div className="courses-page fade-in"><PageHead title="Course Governance & Delivery" sub="Monitor course ownership, faculty allocation, prerequisites, outcome coverage, and delivery performance." right={<button className="btn btn-out" onClick={()=>exportCsv(filtered)}>Export</button>}/>
  <div className="course-health-summary">{[['UNASSIGNED','Unassigned sections'],['OUTCOMES','Missing course outcomes'],['PREREQUISITES','Prerequisite gaps'],['PERFORMANCE','Low performance']].map(([key,label])=><button className={`course-health-card ${filter===key?'active':''}`} key={key} onClick={()=>setFilter(filter===key?'ALL':key)}><b>{count(key)}</b><span>{label}</span></button>)}</div>
  <section className="courses-filters card"><label>Search<input className="inp" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Course code or name"/></label><button className="btn btn-out" onClick={()=>{setQuery('');setFilter('ALL')}}>Reset filters</button></section>
  <section className="card courses-catalog"><header><h2>Course catalog <em>{filtered.length} records</em></h2></header><div className="tbl-scroll"><table className="tbl"><thead><tr><th>Course</th><th>Scope</th><th>Faculty / delivery</th><th>Prerequisite</th><th>CO coverage</th><th>Pass rate</th><th>Status</th></tr></thead><tbody>{filtered.map((x:any)=><tr className="course-row" key={x.id} onClick={()=>setSelected(x)}><td><b className="mono">{x.code}</b><small>{x.title} · {x.credits} credits</small></td><td>{x.dept}<small>{x.program} · Sem {x.semester}</small></td><td>{x.faculty?.join(', ')||'No section'}{x.unassigned_sections>0&&<small className="course-alert">{x.unassigned_sections} unassigned</small>}</td><td>{x.prerequisite||'None'}</td><td className={x.outcome_count?'':'course-alert'}>{x.outcome_count?`${x.outcome_count} COs`:'Missing'}</td><td className={x.pass_rate!=null&&x.pass_rate<60?'course-alert':''}>{x.pass_rate==null?'No results':`${x.pass_rate}%`}</td><td>{x.status}</td></tr>)}</tbody></table></div>{!filtered.length&&<Empty text="No courses match this view."/>}</section>
  {selected&&<Modal title="Course Governance Review" onClose={()=>setSelected(null)}><div className="course-detail"><h3>{selected.code} · {selected.title}</h3><p>{selected.description||'No course description supplied.'}</p><div className="course-detail-grid"><Detail l="Department" v={selected.dept}/><Detail l="Program" v={selected.program}/><Detail l="Credits / LTP" v={`${selected.credits} / ${selected.ltp}`}/><Detail l="Prerequisite" v={selected.prerequisite||'None'}/><Detail l="Faculty" v={selected.faculty?.join(', ')||'No delivery section'}/><Detail l="Course outcomes" v={selected.outcome_count?`${selected.outcome_count} mapped`:'Mapping required'}/><Detail l="Pass rate" v={selected.pass_rate==null?'No published result':`${selected.pass_rate}%`}/><Detail l="Delivery status" v={selected.unassigned_sections?`${selected.unassigned_sections} section(s) unassigned`:'Faculty allocation complete'}/></div></div></Modal>}
 </div>
}
function Detail({l,v}:any){return <div><span>{l}</span><b>{v}</b></div>}
function exportCsv(rows:any[]){const text=[['Code','Course','Department','Program','Faculty','Outcomes','Pass rate'],...rows.map(x=>[x.code,x.title,x.dept,x.program,(x.faculty||[]).join('; '),x.outcome_count,x.pass_rate??''])].map(r=>r.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download='course-governance.csv';a.click();URL.revokeObjectURL(a.href)}
