import { useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import { Empty, Modal, PageHead, Pill, Spinner } from './kit'

const initial = { code:'', title:'', dept_code:'', credits:3, semester:1, regulation:'R2023', course_type:'Core', category:'Professional Core', ltp:'3-0-0', prerequisite:'', description:'', effective_term:'', rationale:'' }
export default function Curriculum() {
  const [courses,setCourses]=useState<any[]|null>(null),[workflow,setWorkflow]=useState<any>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[show,setShow]=useState(false),[selected,setSelected]=useState<any>(null),[reason,setReason]=useState(''),[filter,setFilter]=useState('ALL'),[form,setForm]=useState<any>(initial)
  const [department,setDepartment]=useState(''),[program,setProgram]=useState(''),[regulation,setRegulation]=useState(''),[semester,setSemester]=useState(''),[openSemester,setOpenSemester]=useState<number|null>(null)
  async function load(){try{setError('');const [catalog,queue]=await Promise.all([api.courses(),api.curriculumProposals()]);setCourses(catalog.courses||[]);setWorkflow(queue)}catch(e:any){setError(e.message||'Unable to load curriculum data');setCourses([])}}
  useEffect(()=>{load()},[])
  const departments=useMemo(()=>Array.from(new Set((courses||[]).map(x=>x.dept))).filter(Boolean).sort(),[courses]), semesters=useMemo(()=>Array.from(new Set((courses||[]).map(x=>Number(x.semester)))).sort((a,b)=>a-b),[courses])
  const filtered=useMemo(()=> (courses||[]).filter(x=>(!department||x.dept===department)&&(!program||x.program===program)&&(!regulation||x.regulation===regulation)&&(!semester||Number(x.semester)===Number(semester))),[courses,department,program,regulation,semester])
  const groups=useMemo(()=>semesters.map(n=>({number:n,courses:filtered.filter(x=>Number(x.semester)===n)})).filter(x=>x.courses.length),[semesters,filtered]), proposals=(workflow?.proposals||[]).filter((x:any)=>filter==='ALL'||x.state===filter), pending=(workflow?.proposals||[]).filter((x:any)=>['SUBMITTED','RESUBMITTED'].includes(x.state))
  async function submit(){setSaving(true);try{const created=await api.createCurriculumProposal(form);await api.submitCurriculumProposal(created.proposal.id,created.proposal.status_version);setShow(false);setForm(initial);await load()}catch(e:any){setError(e.message||'Could not submit curriculum proposal')}finally{setSaving(false)}}
  async function decide(action:string){if(!selected)return;if(action!=='approve'&&!reason.trim()){setError('A reason is required for this decision');return}setSaving(true);try{await api.decideCurriculumProposal(selected.id,action,selected.status_version,reason||'Dean curriculum approval');setSelected(null);setReason('');await load()}catch(e:any){setError(e.message||'Could not record curriculum decision')}finally{setSaving(false)}}
  if(!courses)return <Spinner/>
  return <div className="curriculum-page fade-in"><PageHead title="Curriculum Governance" sub="Review curriculum changes, validate academic impact, and maintain controlled versions." right={<><button className="btn btn-out" onClick={load}>Refresh</button>{workflow?.can_propose&&<button className="btn btn-crimson" onClick={()=>setShow(true)}>New curriculum proposal</button>}</>}/>{error&&<div className="calendar-banner warn">{error}</div>}
    <div className="curriculum-governance-summary"><Summary label="Pending decisions" value={pending.length} onClick={()=>setFilter('SUBMITTED')}/><Summary label="Overdue reviews" value={pending.filter((x:any)=>x.due_at&&new Date(x.due_at).getTime()<Date.now()).length} danger onClick={()=>setFilter('SUBMITTED')}/><Summary label="Approved changes" value={(workflow?.proposals||[]).filter((x:any)=>x.state==='APPROVED').length} onClick={()=>setFilter('APPROVED')}/><Summary label="Total proposals" value={(workflow?.proposals||[]).length} onClick={()=>setFilter('ALL')}/></div>
    <section className="curriculum-filters card"><label>Department<select className="select" value={department} onChange={e=>setDepartment(e.target.value)}><option value="">All departments</option>{departments.map(x=><option key={String(x)}>{String(x)}</option>)}</select></label><label>Program<select className="select" value={program} onChange={e=>setProgram(e.target.value)}><option value="">All programs</option>{Array.from(new Set((courses||[]).map(x=>x.program))).filter(Boolean).map(x=><option key={String(x)}>{String(x)}</option>)}</select></label><label>Regulation<select className="select" value={regulation} onChange={e=>setRegulation(e.target.value)}><option value="">All regulations</option>{Array.from(new Set((courses||[]).map(x=>x.regulation))).filter(Boolean).map(x=><option key={String(x)}>{String(x)}</option>)}</select></label><label>Semester<select className="select" value={semester} onChange={e=>setSemester(e.target.value)}><option value="">All semesters</option>{semesters.map(x=><option key={x} value={x}>Semester {x}</option>)}</select></label></section>
    <section className="curriculum-stats"><Stat label="Subjects" value={filtered.length}/><Stat label="Core subjects" value={filtered.filter(x=>x.course_type==='Core').length}/><Stat label="Electives" value={filtered.filter(x=>x.course_type==='Elective').length}/><Stat label="Total credits" value={filtered.reduce((s,x)=>s+Number(x.credits||0),0)}/></section>
    <div className="curriculum-layout"><section className="curriculum-structure card"><header><h2>Curriculum Structure</h2><p>Expand a semester to inspect its subjects.</p></header>{groups.map(g=><section className="curriculum-semester" key={g.number}><button className="curriculum-semester-head" onClick={()=>setOpenSemester(openSemester===g.number?null:g.number)}><span>Semester {g.number}</span><em>{g.courses.length} subjects · {g.courses.reduce((s,x)=>s+Number(x.credits||0),0)} credits</em><b>{openSemester===g.number?'−':'+'}</b></button>{openSemester===g.number&&<div className="curriculum-table-wrap"><table className="tbl curriculum-table"><thead><tr><th>Code</th><th>Subject</th><th>Type</th><th>Credits</th><th>Prerequisite</th><th>Category</th></tr></thead><tbody>{g.courses.map(x=><tr key={x.id}><td><b className="mono">{x.code}</b></td><td>{x.title}</td><td>{x.course_type}</td><td>{x.credits}</td><td>{x.prerequisite||'—'}</td><td>{x.category}</td></tr>)}</tbody></table></div>}</section>)}{!groups.length&&<Empty text="No subjects match the selected filters"/>}</section>
      <aside className="curriculum-summary card"><div className="curriculum-proposal-head"><div><h2>Curriculum Proposals</h2><p className="hint">Review impact and evidence before deciding.</p></div><select className="select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All</option><option value="SUBMITTED">Pending</option><option value="APPROVED">Approved</option><option value="DRAFT">Draft</option></select></div>{proposals.map((x:any)=><button className="curriculum-proposal-row" key={x.id} onClick={()=>{setSelected(x);setReason('')}}><span><b>{x.title}</b><small>{x.payload?.effective_term||'No term'} · {x.payload?.dept_code||'—'}</small></span><Pill s={x.state}/></button>)}{!proposals.length&&<Empty text="No governed changes match this filter"/>}</aside></div>
    {show&&<Modal title="New Curriculum Proposal" onClose={()=>setShow(false)} footer={<><button className="btn btn-out" onClick={()=>setShow(false)}>Cancel</button><button className="btn btn-crimson" disabled={saving} onClick={submit}>{saving?'Submitting...':'Submit for Dean approval'}</button></>}><div className="grid-2"><Field label="Course code"><input className="inp" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></Field><Field label="Course title"><input className="inp" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Department"><input className="inp" value={form.dept_code} onChange={e=>setForm({...form,dept_code:e.target.value})}/></Field><Field label="Effective term"><input className="inp" value={form.effective_term} onChange={e=>setForm({...form,effective_term:e.target.value})} placeholder="2026-Odd"/></Field><Field label="Credits"><input className="inp" type="number" min="1" value={form.credits} onChange={e=>setForm({...form,credits:Number(e.target.value)})}/></Field><Field label="Semester"><input className="inp" type="number" min="1" value={form.semester} onChange={e=>setForm({...form,semester:Number(e.target.value)})}/></Field></div><Field label="Rationale"><textarea className="inp" rows={4} value={form.rationale} onChange={e=>setForm({...form,rationale:e.target.value})}/></Field></Modal>}
    {selected&&<Modal title="Curriculum Proposal Review" onClose={()=>setSelected(null)} footer={<><button className="btn btn-out" onClick={()=>setSelected(null)}>Close</button>{workflow?.can_decide&&pendingStates(selected)&&<><button className="btn btn-out" disabled={saving} onClick={()=>decide('clarification')}>Request clarification</button><button className="btn btn-rose" disabled={saving} onClick={()=>decide('reject')}>Reject</button><button className="btn btn-crimson" disabled={saving} onClick={()=>decide('approve')}>Approve</button></>}</>}><h3>{selected.title}</h3><p>{selected.payload?.description||selected.payload?.rationale||'No additional evidence supplied.'}</p><div className="curriculum-review-grid"><Check label="Effective term" value={selected.payload?.effective_term}/><Check label="Credits" value={selected.payload?.credits}/><Check label="Course type" value={selected.payload?.course_type}/><Check label="Prerequisite" value={selected.payload?.prerequisite||'None'}/></div>{pendingStates(selected)&&<Field label="Decision rationale"><textarea className="inp" rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required for clarification or rejection."/></Field>}<div className="implementation-list"><Check label="CO/PO mappings reviewed" value="Pending"/><Check label="Timetable impact reviewed" value="Pending"/><Check label="Affected batches reviewed" value="Pending"/></div></Modal>}
  </div>
}
function pendingStates(x:any){return ['SUBMITTED','RESUBMITTED'].includes(x?.state)} function Summary({label,value,danger,onClick}:any){return <button className={`curriculum-governance-card ${danger?'danger':''}`} onClick={onClick}><b>{value}</b><span>{label}</span></button>} function Stat({label,value}:any){return <section className="curriculum-stat"><span>{label}</span><b>{value}</b></section>} function Check({label,value}:any){return <div className="curriculum-check"><span>{label}</span><b>{value||'—'}</b></div>} function Field({label,children}:any){return <div className="form-row"><label>{label}</label>{children}</div>}
