import { useEffect, useState } from 'react'
import { api } from '../api'
import { Modal, PageHead, Spinner } from './kit'

export default function FacultyStaff(){
 const [data,setData]=useState<any>(null),[q,setQ]=useState(''),[dept,setDept]=useState(''),[kind,setKind]=useState(''),[page,setPage]=useState(1),[profile,setProfile]=useState<any>(null),[filters,setFilters]=useState({designation:'',status:''})
 const load=(query=q,department=dept,type=kind,p=page,nextFilters=filters)=>api.facultyStaff(query,department,type,p,nextFilters).then(setData)
 useEffect(()=>{load()},[])
 if(!data)return <Spinner/>
 const s=data.summary
 return <div className="fade-in faculty-ref"><PageHead title="Faculty & Staff" sub="Review faculty and staff within your authorized campus."/><div className="faculty-context"><span>Campus-scoped Principal oversight</span><b>•</b><span>Academic year: live institution context</span></div>
 <div className="faculty-kpis"><Metric icon="people" n={s.total} t="Total Faculty & Staff" d="Campus workforce"/><Metric icon="teaching" n={s.teaching} t="Teaching Faculty" d={`${s.total ? Math.round(s.teaching/s.total*100) : 0}% of workforce`}/><Metric icon="staff" n={s.non_teaching} t="Non-Teaching Staff" d={`${s.total ? Math.round(s.non_teaching/s.total*100) : 0}% of workforce`}/><Metric icon="leave" n={s.on_leave} t="On Leave Today" d="Approved leave records"/><Metric icon="vacancy" n={s.vacancies} t="Vacancies" d="Open positions"/></div>
 <div className="faculty-tabs">{[['','All',s.total],['teaching','Teaching',s.teaching],['non_teaching','Non-Teaching',s.non_teaching],['on_leave','On Leave',s.on_leave]].map(([v,t,count]:any)=><button className={kind===v?'active':''} key={t} onClick={()=>{setKind(v);setPage(1);load(q,dept,v,1)}}>{t} <b>{count}</b></button>)}</div>
 <div className="faculty-filter"><input className="inp" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load(q,dept,kind,1)} placeholder="Search by name, employee ID or email"/><label>Department<select className="select" value={dept} onChange={e=>setDept(e.target.value)}><option value="">All Departments</option>{data.departments.map((x:any)=><option key={x.code} value={x.code}>{x.code} · {x.name}</option>)}</select></label><label>Designation<select className="select" value={filters.designation} onChange={e=>setFilters({...filters,designation:e.target.value})}><option value="">All Designations</option>{data.designations.map((x:string)=><option key={x}>{x}</option>)}</select></label><label>Status<select className="select" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All Statuses</option>{data.statuses.map((x:string)=><option key={x}>{x}</option>)}</select></label><button className="btn btn-crimson" onClick={()=>{setPage(1);load(q,dept,kind,1)}}>Apply Filters</button><button className="btn btn-out" onClick={()=>{const next={designation:'',status:''};setQ('');setDept('');setKind('');setFilters(next);setPage(1);load('','','',1,next)}}>Clear</button></div>
 <div className="faculty-table-card"><div className="faculty-table-head">Showing {data.staff.length?(data.page-1)*data.page_size+1:0}–{Math.min(data.page*data.page_size,data.total)} of {data.total} staff members</div><div className="tbl-scroll"><table className="tbl"><thead><tr><th>Employee ID</th><th>Name</th><th>Department</th><th>Designation</th><th>Employee Type</th><th>Leave Status</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.staff.map((x:any)=><tr key={x.id}><td className="mono">{x.employee_id}</td><td><span className="faculty-avatar">{x.name.slice(0,1)}</span><b>{x.name}</b><small>{x.email}</small></td><td>{x.department}</td><td>{x.designation}</td><td><span className={`staff-type ${x.type==='Teaching'?'teaching':'non-teaching'}`}>{x.type}</span></td><td>{x.on_leave?<span className="leave-pill">On Leave</span>:'—'}</td><td><span className={`pill s-${x.status}`}>{x.status}</span></td><td><button className="btn btn-out student-view" onClick={()=>api.facultyProfile(x.id).then(setProfile)}>View</button></td></tr>)}</tbody></table></div><div className="student-pagination"><button className="btn btn-out" disabled={data.page<=1} onClick={()=>{const n=page-1;setPage(n);load(q,dept,kind,n)}}>Previous</button><span>Page {data.page} of {data.total_pages}</span><button className="btn btn-out" disabled={data.page>=data.total_pages} onClick={()=>{const n=page+1;setPage(n);load(q,dept,kind,n)}}>Next</button></div></div>
 {profile&&<Modal title="Faculty Profile" onClose={()=>setProfile(null)}><ProfileTabs data={profile}/></Modal>}</div>
}
function ProfileTabs({data}:any){const x=data.staff;const [tab,setTab]=useState('overview');return <div className="faculty-profile"><header><span className="faculty-avatar large">{x.name.slice(0,1)}</span><div><h3>{x.name}</h3><p>{x.designation} · <span className={`pill s-${x.status}`}>{x.status}</span></p><small>{x.employee_id} · {x.department} · {x.campus}</small></div></header><div className="faculty-profile-stats"><div><b>{x.classes}</b><span>Classes</span></div><div><b>{x.students}</b><span>Students</span></div><div><b>{x.type}</b><span>Employee Type</span></div></div><div className="faculty-modal-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='leave'?'active':''} onClick={()=>setTab('leave')}>Leave</button><button className={tab==='schedule'?'active':''} onClick={()=>setTab('schedule')}>Schedule</button></div>{tab==='overview'&&<div className="faculty-profile-grid"><Box t="Employee Information" rows={[["Employee ID",x.employee_id],["Department",x.department],["Designation",x.designation],["Date of Joining",x.date_joined||'Unavailable']]}/><Box t="Contact & Campus" rows={[["Institutional Email",x.email],["Campus",x.campus],["Phone",'Unavailable']]}/></div>}{tab==='leave'&&(data.leave?.length?<div className="faculty-tab-panel">{data.leave.map((item:any,i:number)=><div className="snap" key={i}><span>{item.kind} · {item.from} to {item.to}</span><b>{item.status} · {item.days} days</b></div>)}</div>:<p className="faculty-empty">No leave records are available.</p>)}{tab==='schedule'&&(data.sections?.length?<div className="faculty-tab-panel">{data.sections.map((s:any,i:number)=><div className="snap" key={i}><span>{s.term} · Section {s.code} · {s.room||'Room unavailable'}</span><b>{s.schedule||'Schedule unavailable'}</b></div>)}</div>:<p className="faculty-empty">No teaching sections are assigned.</p>)}</div>}
function Metric({icon,n,t,d}:any){const glyph:any={people:'♧',teaching:'▣',staff:'▤',leave:'▦',vacancy:'♙',alert:'!'};return <div className="faculty-kpi"><i className={icon}>{glyph[icon]}</i><div><span>{t}</span><b>{n}</b><small>{d}</small></div></div>};function Profile({data}:any){const x=data.staff;return <div className="faculty-profile"><header><span className="faculty-avatar large">{x.name.slice(0,1)}</span><div><h3>{x.name}</h3><p>{x.designation} · <span className={`pill s-${x.status}`}>{x.status}</span></p><small>{x.employee_id} · {x.department}</small></div></header><div className="faculty-profile-stats"><div><b>{x.classes}</b><span>Classes</span></div><div><b>{x.students}</b><span>Students</span></div><div><b>{x.type}</b><span>Employee Type</span></div></div><div className="faculty-profile-grid"><Box t="Employee Information" rows={[["Employee ID",x.employee_id],["Department",x.department],["Date of Joining",x.date_joined||'Unavailable']]}/><Box t="Contact & Campus" rows={[["Institutional Email",x.email],["Campus",x.campus],["Designation",x.designation]]}/></div><h4>Current Teaching / Assignment</h4>{data.sections.length?data.sections.map((s:any,i:number)=><div className="snap" key={i}><span>{s.term} · Section {s.code}</span><b>{s.schedule||'Schedule unavailable'}</b></div>):<p className="hint">No current teaching sections are assigned.</p>}</div>};function Box({t,rows}:any){return <section><h4>{t}</h4>{rows.map(([k,v]:any)=><div className="snap" key={k}><span>{k}</span><b>{v}</b></div>)}</section>}
