import { useEffect, useState } from 'react';
import { api } from '../api';
import { Empty, Spinner } from './kit';

const attentionRoutes: Record<string, string> = { sections_without_faculty: 'hod_allocations', sections_missing_timetable: 'hod_sections', attendance_sessions_pending: 'hod_attendance', at_risk_students: 'hod_risk', marks_reviews: 'hod_reviews_marks' };
const attentionLabels: Record<string, string> = { sections_without_faculty: 'Sections without faculty', sections_missing_timetable: 'Sections missing timetable', attendance_sessions_pending: 'Attendance sessions pending', at_risk_students: 'At-Risk Students', marks_reviews: 'Marks reviews awaiting HOD' };
const readinessHelp: Record<string, string> = { 'Faculty Allocation Coverage': 'Allocated sections', 'Timetable Coverage': 'Scheduled sections', 'Attendance Finalization': 'Finalized sessions', 'Course Coverage': 'Courses offered this term' };

export default function HodOverview({ user, go }: any) {
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState('');
  const [refreshedAt, setRefreshedAt] = useState<Date | null>(null);
  const load = async () => { setError(''); try { setData(await api.hodDashboard()); setRefreshedAt(new Date()); } catch (reason: any) { setError(reason.message || 'Department overview could not be loaded.'); } };
  useEffect(() => { load(); }, []);
  if (error && !data) return <Empty icon="!" text={error} />;
  if (!data) return <Spinner />;

  const kpis = data.kpis || {}, reviews = data.reviews || {}, operations = data.operations || {}, health = data.student_health || {};
  const primary = [
    ['Active Faculty', kpis.active_faculty, 'Faculty in department', 'hod_faculty'], ['Active Students', kpis.department_students, 'Current department cohort', 'hod_students'],
    ['Active Sections', kpis.active_sections, 'Stored-term sections', 'hod_sections'], ['Allocation Readiness', percentage(data.readiness?.faculty_allocation), ratio(data.readiness?.faculty_allocation), 'hod_allocations'],
    ['Attendance Finalization', percentage(data.readiness?.attendance_finalization), ratio(data.readiness?.attendance_finalization), 'hod_attendance'], ['At-Risk Students', kpis.at_risk_students, 'Needs academic follow-up', 'hod_risk'],
  ];
  const readiness = [['Faculty Allocation Coverage', data.readiness?.faculty_allocation], ['Timetable Coverage', data.readiness?.timetable], ['Attendance Finalization', data.readiness?.attendance_finalization], ['Course Coverage', data.readiness?.course_coverage]];
  const reviewCards = [['Marks', reviews.marks_reviews, 'hod_reviews_marks'], ['Attendance Corrections', reviews.attendance_corrections, 'hod_reviews_attendance_corrections'], ['Faculty Leave', reviews.faculty_leave, 'hod_reviews_faculty_leave'], ['Mentoring Referrals', reviews.mentoring_referrals, 'hod_reviews_mentoring_referrals']];
  const operationCards = [['Programs & Courses', kpis.active_sections, 'Current-term sections', 'hod_courses'], ['Teaching Allocations', operations.teaching_active, 'Active allocations', 'hod_allocations'], ['Sections & Timetable', percentage(data.readiness?.timetable), 'Timetable coverage', 'hod_sections'], ['Examination Coordination', operations.awaiting_hod_review, 'Awaiting HOD review', 'hod_exams']];

  return <main className="hod-command fade-in">
    <header className="hod-command-header"><div><p>DEPARTMENT ACADEMIC COMMAND CENTER</p><h1>Department Overview</h1><span>{data.department?.name} · {data.department?.campus}{data.department?.term ? ` · Stored term: ${data.department.term}` : ''}</span></div><div className="hod-command-tools"><small>{refreshedAt ? `Last refreshed ${refreshedAt.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : 'Loading current data'}</small><button className="btn btn-out" type="button" onClick={load}>Refresh</button><div className="hod-command-user"><b>{user.name?.[0] || 'H'}</b><span><strong>{user.name || 'Head of Department'}</strong><small>{user.active_role || 'Head of Department'}</small></span></div></div></header>
    {error && <p className="hod-allocation-message error">{error}</p>}
    <section className="hod-command-kpis" aria-label="Department key metrics">{primary.map(([label, value, support, target]: any, index) => <button key={label} className={`hod-command-kpi kpi-${index}`} onClick={() => go(target)} type="button"><span>{label}</span><b>{value ?? '—'}</b><small>{support}</small></button>)}</section>
    <section className="hod-command-card hod-command-readiness"><header><div><p>Operational coverage</p><h2>Department Readiness</h2></div><button type="button" onClick={() => go('hod_planning')}>Open Department Planning →</button></header><div className="hod-command-readiness-grid">{readiness.map(([label, item]: any) => <button key={label} type="button" onClick={() => go(label === 'Faculty Allocation Coverage' ? 'hod_allocations' : label === 'Timetable Coverage' ? 'hod_sections' : label === 'Attendance Finalization' ? 'hod_attendance' : 'hod_courses')}><div><span>{label}</span><b>{percentage(item)}</b></div><small>{ratio(item)} · {readinessHelp[label]}</small><i><em style={{ width: `${item?.percentage || 0}%` }} /></i></button>)}</div></section>
    <section className="hod-command-priority"><Panel title="Needs Attention" eyebrow="Priority action">{data.attention?.filter((item: any) => item.count > 0).map((item: any) => <button className="hod-command-attention" key={item.key} onClick={() => go(attentionRoutes[item.key])} type="button"><span>{attentionLabels[item.key] || item.key}</span><b>{item.count}</b><em>Open →</em></button>)}{!data.attention?.some((item: any) => item.count > 0) && <p className="hod-command-empty">No recorded department gaps require action.</p>}</Panel><Panel title="My Reviews" eyebrow="Reviewer inbox" action="Open My Reviews" onAction={() => go('hod_reviews')}><div className="hod-command-reviews">{reviewCards.map(([label, value, target]: any) => <button key={label} onClick={() => go(target)} type="button"><b>{value ?? 0}</b><span>{label}</span><small>Open review queue →</small></button>)}</div></Panel></section>
    <section className="hod-command-card hod-command-operations"><header><div><p>Department delivery</p><h2>Academic Operations</h2></div></header><div>{operationCards.map(([label, value, support, target]: any) => <button key={label} onClick={() => go(target)} type="button"><span>{label}</span><b>{value ?? '—'}</b><small>{support}</small><em>Open →</em></button>)}</div></section>
    <section className="hod-command-card hod-command-health"><header><div><p>Student outcomes</p><h2>Student Academic Health</h2></div><button type="button" onClick={() => go('hod_risk')}>View At-Risk Students →</button></header><div>{[['At Risk', health.at_risk], ['With Backlogs', health.backlogs], ['Attendance Risk', health.attendance_risk], ['Academic Risk', health.academic_risk], ['Multiple Risks', health.multiple_risks]].map(([label, value], index) => <button className={`health-${index}`} key={String(label)} onClick={() => go('hod_risk')} type="button"><b>{value ?? 0}</b><span>{label}</span></button>)}</div></section>
    <section className="hod-command-bottom"><Panel title="My Requests" eyebrow="HOD-originated workflows" action="View All Requests" onAction={() => go('hod_requests')}><div className="hod-command-list">{data.requests?.map((item: any, index: number) => <button key={`${item.label}-${index}`} onClick={() => go('hod_requests')} type="button"><span>{item.label}</span><b className="hod-command-status">{title(item.status)}</b><time>{formatDate(item.updated_at)}</time></button>)}{!data.requests?.length && <p className="hod-command-empty">No current HOD-originated requests.</p>}</div></Panel><Panel title="Recent Department Activity" eyebrow="Privacy-safe audit activity" action="View Department Audit" onAction={() => go('hod_department_audit')}><div className="hod-command-list">{data.activity?.map((item: any, index: number) => <button key={`${item.at}-${index}`} onClick={() => go('hod_department_audit')} type="button"><span>{item.description}</span><b>{item.resource}</b><time>{formatDate(item.at)} · {title(item.status)}</time></button>)}{!data.activity?.length && <p className="hod-command-empty">No safe departmental activity is available.</p>}</div></Panel></section>
  </main>;
}

function Panel({ title, eyebrow, action, onAction, children }: any) { return <section className="hod-command-card"><header><div>{eyebrow && <p>{eyebrow}</p>}<h2>{title}</h2></div>{action && <button type="button" onClick={onAction}>{action} →</button>}</header>{children}</section>; }
function percentage(item: any) { return item?.percentage === null || item?.percentage === undefined ? '—' : `${item.percentage}%`; }
function ratio(item: any) { return item?.numerator === undefined || item?.denominator === undefined ? '—' : `${item.numerator} / ${item.denominator}`; }
function title(value: any) { return String(value || '—').replace(/_/g, ' ').replace(/\b\w/g, letter => letter.toUpperCase()); }
function formatDate(value: string) { return value ? new Date(value).toLocaleString() : '—'; }
