import { useEffect, useState } from 'react'
import { api } from '../api'
import { PageHead, Spinner } from './kit'

export default function PrincipalExaminations() {
  const [data, setData] = useState<any>(null), [error, setError] = useState(''), [selected, setSelected] = useState<any>(null), [detail, setDetail] = useState<any>(null), [detailError, setDetailError] = useState(''), [tab, setTab] = useState('assessments'), [refreshing, setRefreshing] = useState(false)
  const load = () => { setRefreshing(true); setError(''); api.examSections().then(setData).catch((e: any) => setError(e.message || 'Unable to load examination oversight data.')).finally(() => setRefreshing(false)) }
  const open = (row: any) => { setSelected(row); setDetail(null); setDetailError(''); setTab('assessments'); api.examSectionOversight(row.id).then(setDetail).catch((e: any) => setDetailError(e.message || 'Unable to load examination details.')) }
  useEffect(() => { load() }, [])
  if (!data && !error) return <Spinner />
  if (error && !data) return <div className="empty-state"><h3>Unable to load examination oversight data.</h3><p>{error}</p><button className="btn btn-out" onClick={load}>Retry</button></div>
  return <div className="fade-in exam-oversight"><PageHead title="Examinations" sub="Principal examination oversight: readiness, submissions, results, and exceptions." /><section className="card"><div className="card-h"><h3>Section Readiness Register</h3><span className="hint">Read-only oversight · <button className="linkish" onClick={load} disabled={refreshing}>{refreshing ? 'Refreshing...' : 'Refresh'}</button></span></div><div className="tbl-scroll"><table className="tbl"><thead><tr><th>Course</th><th>Section</th><th>Faculty</th><th>Students</th><th>Assessments</th><th>Marks status</th><th>Result status</th><th /></tr></thead><tbody>{(data.sections || []).map((row: any) => <tr key={row.id}><td><b>{row.course_code}</b><small>{row.course_title}</small></td><td>{row.section}</td><td>{row.faculty?.name || 'Unassigned'}</td><td>{row.students ?? 0}</td><td>{row.assessments ?? 0}</td><td>{(row.marks_lifecycle_statuses || []).join(', ') || 'Not started'}</td><td>{row.result_status || 'Not started'}</td><td><button className="btn btn-out" onClick={() => open(row)}>View</button></td></tr>)}</tbody></table>{!data.sections?.length && <p className="principal-empty">No examination sections are available in the authorized campus.</p>}</div></section>{selected && <div className="exam-detail-backdrop" role="presentation" onMouseDown={() => setSelected(null)}><section className="exam-detail card" role="dialog" aria-modal="true" onMouseDown={event => event.stopPropagation()}>{!detail && !detailError && <Spinner />}{detailError && <div className="empty-state"><h3>Unable to load examination details.</h3><p>{detailError}</p><button className="btn btn-out" onClick={() => open(selected)}>Retry</button></div>}{detail && <Detail data={detail} tab={tab} setTab={setTab} close={() => setSelected(null)}/>}</section></div>}</div>
}

function Detail({ data, tab, setTab, close }: any) { const section = data.section || {}; return <><div className="card-h"><div><h3>{section.course_code || 'Section'} · {section.section || ''}</h3><span>{section.course_title || 'Course detail'}</span></div><button className="icon-btn" onClick={close} aria-label="Close examination details">×</button></div><div className="exam-tabs">{[['assessments', 'Assessments'], ['marks', 'Marks status'], ['results', 'Results'], ['exceptions', `Exceptions (${(data.exceptions || []).length})`], ['audit', 'Audit']].map(([key, text]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}>{text}</button>)}</div>{tab === 'assessments' && <Rows items={data.assessments || []} columns={['Assessment', 'Type', 'Max marks', 'Status', 'Scheduled']} render={(item: any) => [item.name, item.type, item.max_marks, item.marks_status || item.status, item.scheduled_at ? new Date(item.scheduled_at).toLocaleString() : 'Not recorded']}/>} {tab === 'marks' && <Rows items={(data.assessments || []).flatMap((item: any) => item.marks || [])} columns={['Roll no.', 'Student', 'Score', 'Status']} render={(item: any) => [item.roll_no, item.name, item.score ?? 'Not entered', item.mark_status || 'Not recorded']}/>} {tab === 'results' && <div className="principal-empty">Result status: <b>{data.result?.status || 'Not started'}</b><p>{data.timetable?.length ? `${data.timetable.length} timetable entries available.` : 'No timetable entries are available for this section.'}</p></div>} {tab === 'exceptions' && <Rows items={data.exceptions || []} columns={['Severity', 'Issue', 'Current owner', 'Required action', 'Status']} render={(item: any) => [item.severity, item.issue, item.current_owner, item.required_action, item.status]}/>} {tab === 'audit' && <Rows items={data.audit || []} columns={['Action', 'Actor', 'Change', 'Time']} render={(item: any) => [item.action, item.actor, `${item.previous || '—'} → ${item.current || '—'}`, item.at ? new Date(item.at).toLocaleString() : 'Not recorded']}/>}</> }
function Rows({ items, columns, render }: any) { return items.length ? <div className="tbl-scroll"><table className="tbl"><thead><tr>{columns.map((column: string) => <th key={column}>{column}</th>)}</tr></thead><tbody>{items.map((item: any, index: number) => <tr key={item.id || index}>{render(item).map((value: any, valueIndex: number) => <td key={valueIndex}>{value}</td>)}</tr>)}</tbody></table></div> : <p className="principal-empty">No records are available for this section.</p> }