import { useEffect, useState } from 'react'
import { api } from '../api'
import { Modal, PageHead, Spinner } from './kit'

export default function PrincipalAtRisk() {
  const initial = { academicYear: '', semester: '', program: '', department: '', risk: 'at-risk' }
  const [filters, setFilters] = useState<any>(initial), [q, setQ] = useState(''), [data, setData] = useState<any>(null), [error, setError] = useState(''), [profile, setProfile] = useState<any>(null), [page, setPage] = useState(1)
  const load = (next = filters, query = q, nextPage = page) => { setData(null); setError(''); api.students(query, next.department || '', nextPage, 25, next).then(setData).catch(() => setError('Unable to load student risk data.')) }
  useEffect(() => { load(initial, '', 1) }, [])
  if (!data && !error) return <Spinner />
  if (error) return <div className="empty-state"><h3>Unable to load student risk data.</h3><button className="btn btn-crimson" onClick={() => load()}>Retry</button></div>

  return <div className="fade-in students-ref principal-at-risk"><PageHead title="At-Risk Students" sub="Monitor students requiring academic or attendance attention within your authorized campus." />
    <div className="students-kpis"><Metric label="Total At-Risk" value={data.summary?.at_risk ?? data.total ?? 0}/><Metric label="Attendance Risk" value={data.summary?.attendance_risk ?? '—'}/><Metric label="Academic Risk" value={data.summary?.academic_risk ?? '—'}/><Metric label="Current Backlogs" value={data.summary?.backlogs ?? '—'}/><Metric label="Average Attendance" value={data.summary?.average_attendance == null ? '—' : `${data.summary.average_attendance}%`}/><Metric label="Average CGPA" value={data.summary?.average_cgpa ?? '—'}/></div>
    <div className="students-filter"><label>Academic Year<select className="select" value={filters.academicYear} onChange={e => setFilters({ ...filters, academicYear: e.target.value })}><option value="">All Years</option>{(data.filter_options?.academic_years || []).map((x: string) => <option key={x}>{x}</option>)}</select></label><label>Semester<select className="select" value={filters.semester} onChange={e => setFilters({ ...filters, semester: e.target.value })}><option value="">All Semesters</option>{(data.filter_options?.semesters || []).map((x: number) => <option key={x} value={x}>Semester {x}</option>)}</select></label><label>Department<select className="select" value={filters.department} onChange={e => setFilters({ ...filters, department: e.target.value })}><option value="">All Departments</option>{(data.filter_options?.departments || []).map(([id, name]: any) => <option key={id} value={id}>{name}</option>)}</select></label><label>Program<select className="select" value={filters.program} onChange={e => setFilters({ ...filters, program: e.target.value })}><option value="">All Programs</option>{(data.filter_options?.programs || []).map(([id, name]: any) => <option key={id} value={id}>{name}</option>)}</select></label><input className="inp" value={q} onChange={e => setQ(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') { setPage(1); load(filters, q, 1) } }} placeholder="Search student name, register number or email"/><button className="btn btn-crimson" onClick={() => { setPage(1); load(filters, q, 1) }}>Filter</button><button className="btn btn-out" onClick={() => { setFilters(initial); setQ(''); setPage(1); load(initial, '', 1) }}>Clear</button></div>
    <section className="card"><div className="card-h"><h3>Risk Register</h3><span className="hint">{data.total ?? data.students?.length ?? 0} students</span></div><div className="tbl-scroll"><table className="tbl"><thead><tr><th>Student</th><th>Register no.</th><th>Department</th><th>Program</th><th>Semester</th><th>Attendance</th><th>CGPA</th><th>Backlogs</th><th>Risk</th><th /></tr></thead><tbody>{(data.students || []).map((student: any) => <tr key={student.id}><td><b>{student.name}</b><small>{student.email}</small></td><td className="mono">{student.roll_no}</td><td>{student.department_name || student.dept || '—'}</td><td>{student.program || '—'}</td><td>{student.semester}</td><td>{student.attendance_pct == null ? 'Unavailable' : `${student.attendance_pct}%`}</td><td>{student.cgpa == null ? '—' : Number(student.cgpa).toFixed(2)}</td><td>{student.current_backlogs ?? student.backlogs ?? 0}</td><td><span className="tag">{(student.risk_reasons || ['At risk']).join(' · ')}</span></td><td><button className="btn btn-out" onClick={() => api.studentProfile(student.id).then(setProfile).catch(() => setError('Unable to load student details.'))}>View</button></td></tr>)}</tbody></table>{!data.students?.length && <p className="principal-empty">No students match the current risk register.</p>}</div>{data.total_pages > 1 && <div className="table-pager"><button className="btn btn-out" disabled={data.page <= 1} onClick={() => { const next = data.page - 1; setPage(next); load(filters, q, next) }}>Previous</button><span>Page {data.page} of {data.total_pages}</span><button className="btn btn-out" disabled={data.page >= data.total_pages} onClick={() => { const next = data.page + 1; setPage(next); load(filters, q, next) }}>Next</button></div>}</section>
    {profile && <Modal title="Student Risk Detail" onClose={() => setProfile(null)}><div className="calendar-detail"><h3>{profile.student?.name}</h3><p>{profile.student?.roll_no} · {profile.student?.campus || 'Authorized campus'}</p><p>Attendance / CGPA / Backlogs: {profile.student?.attendance_pct == null ? 'Unavailable' : `${profile.student.attendance_pct}%`} / {profile.student?.cgpa ?? '—'} / {profile.student?.current_backlogs ?? 0}</p><p>Risk factors: {(profile.student?.risk_reasons || []).join(' · ') || 'Unavailable'}</p></div></Modal>}
  </div>
}

function Metric({ label, value }: any) { return <div className="students-kpi"><div><span>{label}</span><b>{value}</b></div></div> }