import { useEffect, useState } from 'react'
import { api } from '../api'
import { Modal, PageHead, Spinner } from './kit'

const initial = { academicYear: '2026-27', semester: '', program: '', department: '', risk: 'at-risk' }

export default function PrincipalAtRisk() {
  const [filters, setFilters] = useState<any>(initial), [q, setQ] = useState(''), [data, setData] = useState<any>(null), [error, setError] = useState(''), [profile, setProfile] = useState<any>(null), [page, setPage] = useState(1)
  const load = (next = filters, query = q, nextPage = page) => { setData(null); setError(''); api.students(query, next.department || '', nextPage, 25, next).then(setData).catch(() => setError('Unable to load student data.')) }
  useEffect(() => { load(initial, '', 1) }, [])
  if (!data && !error) return <Spinner />
  if (error) return <div className="empty-state"><h3>Unable to load student data.</h3><p>The student risk register could not be retrieved.</p><button className="btn btn-crimson" onClick={() => load()}>Retry</button></div>
  const s = data.summary, options = data.filter_options
  return <div className="fade-in students-ref principal-at-risk"><PageHead title="At-Risk Students" sub="Monitor students requiring academic or attendance attention within your authorized campus." />
    <div className="students-context">Risk is derived only from attendance below 75%, CGPA below 6.5, or active examination backlogs.</div>
    <div className="students-kpis"><Metric label="Total At-Risk" value={s.at_risk}/><Metric label="Attendance Risk" value={s.attendance_risk}/><Metric label="Academic Risk" value={s.academic_risk}/><Metric label="Current Backlogs" value={s.backlogs}/><Metric label="Average Attendance" value={s.average_attendance == null ? '—' : `${s.average_attendance}%`}/><Metric label="Average CGPA" value={s.average_cgpa ?? '—'}/></div>
    <div className="students-filter"><label>Academic Year<select className="select" value={filters.academicYear} onChange={e => setFilters({ ...filters, academicYear: e.target.value })}>{options.academic_years.map((x: string) => <option key={x}>{x}</option>)}</select></label><label>Semester<select className="select" value={filters.semester} onChange={e => setFilters({ ...filters, semester: e.target.value })}><option value="">All Semesters</option>{options.semesters.map((x: number) => <option key={x} value={x}>Semester {x}</option>)}</select></label><label>Department<select className="select" value={filters.department} onChange={e => setFilters({ ...filters, department: e.target.value })}><option value="">All Departments</option>{options.departments.map(([id, name]: any) => <option key={id} value={id}>{name}</option>)}</select></label><label>Program<select className="select" value={filters.program} onChange={e => setFilters({ ...filters, program: e.target.value })}><option value="">All Programs</option>{options.programs.map(([id, name]: any) => <option key={id} value={id}>{name}</option>)}</select></label><input className="inp" value={q} onChange={e => setQ(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') { setPage(1); load(filters, q, 1) } }} placeholder="Search student name, register number or email"/><button className="btn btn-crimson" onClick={() => { setPage(1); load(filters, q, 1) }}>Filter</button><button className="btn btn-out" onClick={() => { setFilters(initial); setQ(''); setPage(1); load(initial, '', 1) }}>Clear</button></div>
    <section className="students-table-card"><div className="students-table-head"><span>{data.total} students currently match the selected risk filters</span><span>Read-only Principal oversight</span></div><div className="tbl-scroll"><table className="tbl students-table"><thead><tr><th>Student</th><th>Register no.</th><th>Department</th><th>Program</th><th>Semester</th><th>Attendance</th><th>CGPA</th><th>Backlogs</th><th>Primary risk</th><th>Action</th></tr></thead><tbody>{data.students.map((student: any) => <tr key={student.id}><td><b>{student.name}</b><small>{student.email}</small></td><td className="mono">{student.roll_no}</td><td>{student.department_name || student.dept}</td><td>{student.program}</td><td>{student.semester}</td><td>{student.attendance_pct == null ? 'Unavailable' : `${student.attendance_pct}%`}</td><td>{Number(student.cgpa).toFixed(2)}</td><td>{student.current_backlogs}</td><td><Risk student={student}/></td><td><button className="btn btn-out student-view" onClick={() => api.studentProfile(student.id).then(setProfile).catch(() => setError('Unable to load student details.'))}>View</button></td></tr>)}</tbody></table>{!data.students.length && <p className="principal-empty">No students found for the selected academic year.</p>}</div>{data.total_pages > 1 && <div className="table-pager"><button className="btn btn-out" disabled={data.page <= 1} onClick={() => { const next = data.page - 1; setPage(next); load(filters, q, next) }}>Previous</button><span>Page {data.page} of {data.total_pages}</span><button className="btn btn-out" disabled={data.page >= data.total_pages} onClick={() => { const next = data.page + 1; setPage(next); load(filters, q, next) }}>Next</button></div>}</section>
    {profile && <Modal title="Student Risk Detail" onClose={() => setProfile(null)}><RiskDetail profile={profile}/></Modal>}
  </div>
}
function Metric({ label, value }: any) { return <div className="students-kpi"><div><span>{label}</span><b>{value}</b></div></div> }
function Risk({ student }: any) { return <span className="student-risk warning">{(student.risk_reasons || []).join(' · ') || 'At risk'}</span> }
function RiskDetail({ profile }: any) { const s = profile.student; return <div className="calendar-detail"><h3>{s.name}</h3><div className="snap"><span>Register number / Campus</span><b>{s.roll_no} · {s.campus || 'Authorized campus'}</b></div><div className="snap"><span>Academic year / Program / Semester</span><b>{s.academic_year || 'Unavailable'} · {s.program || 'Unavailable'} · Semester {s.semester}</b></div><div className="snap"><span>Risk level / factors</span><b>{s.risk_level || 'Unavailable'} · {(s.risk_reasons || []).join(' · ') || 'No risk factors available'}</b></div><div className="snap"><span>Attendance / CGPA / Backlogs</span><b>{s.attendance_pct == null ? 'Unavailable' : `${s.attendance_pct}%`} / {Number(s.cgpa).toFixed(2)} / {s.current_backlogs}</b></div><p>No historical risk records are available.</p></div> }
