import { useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import { Spinner } from './kit'

export default function PrincipalDashboard({ user, go }: { user: any; go: (view: string) => void }) {
  const [year, setYear] = useState(''); const [studentSemester, setStudentSemester] = useState(''); const [data, setData] = useState<any>(null)
  useEffect(() => { setData(null); api.principalOverview(year, studentSemester).then(next => { setData(next); if (!year) setYear(next.filters.selected_year) }).catch(() => setData({ error: true })) }, [year, studentSemester])
  if (!data) return <Spinner />
  if (data.error) return <div className="principal-empty">Dashboard data could not be loaded.</div>
  const k = data.kpis; const p = data.performance
  const cards = [['Total Students', k.students, 'students', 'students'], ['Faculty & Staff', k.faculty, 'staff', 'faculty_staff'], ["Today's Attendance", k.attendance == null ? '—' : `${k.attendance}%`, 'attendance', 'attendance'], ['Needs My Decision', k.decisions, 'decision', 'approvals'], ['At Risk Students', k.risk_students, 'risk', 'students'], ['Critical Alerts', k.critical_alerts, 'alert', 'workflows']]
  return <div className="principal-dashboard fade-in">
    <section className="principal-welcome"><div><h1>Good morning, Principal <span>👋</span></h1><p>{user.scope || 'Campus'} <b>•</b> {user.office}</p></div><div className="principal-filters"><label>ACADEMIC YEAR<select value={year} onChange={e => setYear(e.target.value)}>{data.filters.academic_years.map((x: string) => <option key={x}>{x}</option>)}</select></label><label>SEMESTER<select value={studentSemester} onChange={e => setStudentSemester(e.target.value)}><option value="">All Semesters</option>{data.filters.student_semesters.map((x: number) => <option key={x} value={x}>Semester {x}</option>)}</select></label></div></section>
    <div className="principal-kpis">{cards.map(([label, value, kind, target]) => <button key={String(label)} className="principal-kpi" onClick={() => { if (label === 'At Risk Students') sessionStorage.setItem('principal-student-risk', 'at-risk'); go(String(target)) }} type="button"><span className={`principal-icon ${kind}`}><DashboardIcon kind={String(kind)} /></span><div><span>{label}</span><b>{value}</b><small>View details</small></div></button>)}</div>
    <div className="principal-grid principal-top-grid"><Panel title="Needs My Decision" icon="decision" action="View all" go={() => go('approvals')}><List rows={data.workflows} click={() => go('approvals')} empty="No decisions are waiting for your office." /></Panel><Panel title="Monthly Student Attendance Trend" icon="attendance" action="Open details" go={() => go('attendance')}><Trend rows={data.attendance.trend} today={data.attendance.today} /></Panel><Panel title="Academic Performance (Overall)" icon="performance" action="Open analytics" go={() => go('analytics')}><div className="principal-performance"><div className="performance-ring"><b>{p.average_cgpa}</b><span>Avg. CGPA</span></div><div className="performance-copy"><p><i className="blue" />Distinction: {p.bands.distinction}</p><p><i className="green" />First Class: {p.bands.first}</p><p><i className="orange" />Second Class: {p.bands.second}</p><div className="performance-minis"><Mini value={`${p.pass_rate ?? '—'}%`} label="Pass Rate"/><Mini value={p.at_risk} label="At Risk"/><Mini value={p.backlogs} label="Backlogs"/></div></div></div></Panel></div>
    <div className="principal-grid principal-middle-grid"><Panel title="Examination Overview" icon="exam" action="Open Exams" go={() => go('examinations')}><Metrics values={[[data.examinations.assessments, 'Upcoming Exams', 'exam'], [data.examinations.marks_submitted, 'Marks Submitted', 'decision'], [data.examinations.pending_moderation, 'Pending Moderation', 'alert'], [0, 'Readiness Issues', 'risk']]}/></Panel><Panel title="Student Welfare" icon="welfare" action="Open Welfare" go={() => go('grievance')}><Metrics values={[[data.welfare.at_risk, 'At Risk Students', 'risk'], [data.welfare.grievances, 'Open Grievances', 'welfare'], [data.welfare.discipline, 'Discipline Cases', 'alert'], [data.welfare.critical, 'Critical Welfare Cases', 'risk']]}/></Panel><Panel title="Campus Operations" icon="operations" action="Open Operations" go={() => go('assets')}><Metrics values={[[data.operations.maintenance, 'Maintenance Alerts', 'operations'], [data.operations.procurement, 'Procurement Pending', 'decision'], [data.operations.asset_requests, 'Asset Requests', 'assets'], [data.operations.facilities, 'Facilities Alerts', 'alert']]}/></Panel></div>
    <div className="principal-grid principal-bottom-grid"><Panel title="Recent Notifications" icon="alert" action="View all" go={() => go('workflows')}><List rows={data.notifications} click={() => go('workflows')} empty="No notifications for this account." /></Panel><Panel title="Quick Access"><div className="principal-quick">{[['My Approvals','approvals','decision'],['Escalations','workflows','alert'],['Delegations','delegation','staff'],['Reports','analytics','performance'],['Campus Directory','directory','students'],['Audit','audit','exam']].map(([label,target,icon]) => <button key={label} onClick={() => go(target)}><b><DashboardIcon kind={icon}/></b>{label}</button>)}</div></Panel><Panel title="Academic Calendar" icon="attendance" action="View calendar" go={() => go('academic_calendar')}><p className="principal-empty">Selected: {year} · {studentSemester ? `Semester ${studentSemester}` : 'All Semesters'}</p></Panel></div>
  </div>
}
function Panel({ title, icon, action, go, children }: any) { return <section className="principal-panel"><header><h2>{icon && <span className="panel-title-icon"><DashboardIcon kind={icon} /></span>}{title}</h2>{action && <button onClick={go}>{action}</button>}</header>{children}</section> }
function Metrics({ values }: any) { return <div className="principal-metric-grid">{values.map(([v,l,icon]: any[]) => <div key={l}><span className="metric-icon"><DashboardIcon kind={icon || 'decision'} /></span><b>{v}</b><span>{l}</span></div>)}</div> }
function Mini({ value, label }: any) { return <div><b>{value}</b><small>{label}</small></div> }
function List({ rows, click, empty }: any) { return <div className="principal-decision-list">{rows.length ? rows.slice(0,5).map((r: any) => <button className="principal-decision" key={r.id} onClick={click}><span className="decision-mark"><DashboardIcon kind={r.state ? 'decision' : 'alert'} /></span><span><b>{r.title}</b><small>{r.label || r.severity || 'Notification'}</small></span><em>{r.state || 'new'}</em></button>) : <p className="principal-empty">{empty}</p>}</div> }
function Trend({ rows, today }: any) {
  const [activeIndex, setActiveIndex] = useState<number | null>(null)
  const points = rows.map((row: any, index: number) => ({ ...row, index, x: 16 + index * 54, y: row.value === null ? null : 170 - (Number(row.value) / 100) * 135 }))
  const line = points.filter((point: any) => point.y !== null).map((point: any, index: number) => `${index ? 'L' : 'M'} ${point.x} ${point.y}`).join(' ')
  const active = activeIndex === null ? null : points[activeIndex]
  return <div className="principal-chart"><div className="chart-grid"/>{line ? <><div className={`attendance-detail${active ? ' visible' : ''}`} role="status" aria-live="polite">{active && <><b>{active.label}</b><span>{active.value}% student attendance</span><small>Monthly average</small></>}</div><svg className="attendance-svg" viewBox="0 0 300 190" preserveAspectRatio="none"><path d={line} /><path d={line} className="attendance-area" />{points.filter((point: any) => point.y !== null).map((point: any) => <g key={point.label} className={`attendance-point${activeIndex === point.index ? ' active' : ''}`} role="button" tabIndex={0} aria-label={`${point.label}: ${point.value}% student attendance`} onMouseEnter={() => setActiveIndex(point.index)} onFocus={() => setActiveIndex(point.index)} onClick={() => setActiveIndex(point.index)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); setActiveIndex(point.index) } }}><circle cx={point.x} cy={point.y} r="4"/><text x={point.x} y="187">{point.label}</text><text x={point.x} y={point.y - 9}>{point.value}%</text></g>)}</svg></> : <div className="chart-empty">No attendance has been recorded for this selection.</div>}<div className="chart-legend"><span><DashboardIcon kind="attendance" /> Today: {today == null ? 'No records' : `${today}%`} · monthly averages</span></div></div>
}

function DashboardIcon({ kind }: { kind: string }) {
  const shared = { viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: 1.9, strokeLinecap: 'round' as const, strokeLinejoin: 'round' as const }
  switch (kind) {
    case 'students': return <svg {...shared}><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M20 8v6M23 11h-6"/></svg>
    case 'staff': return <svg {...shared}><circle cx="9" cy="7" r="4"/><path d="M2 21v-2a4 4 0 0 1 4-4h6a4 4 0 0 1 4 4v2"/><path d="M19 4v6M22 7h-6"/></svg>
    case 'attendance': return <svg {...shared}><rect x="3" y="4" width="18" height="17" rx="2"/><path d="M8 2v4M16 2v4M3 9h18M8 14l2 2 4-4"/></svg>
    case 'decision': return <svg {...shared}><path d="M9 11l2 2 4-4"/><path d="M20 11.5V19a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h9"/><path d="M17 3h4v4"/></svg>
    case 'risk': return <svg {...shared}><path d="M12 3 3 20h18L12 3Z"/><path d="M12 9v4M12 17h.01"/></svg>
    case 'alert': return <svg {...shared}><path d="M18 8a6 6 0 1 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg>
    case 'exam': return <svg {...shared}><path d="M4 4h16v16H4zM8 8h8M8 12h5M8 16h4"/></svg>
    case 'welfare': return <svg {...shared}><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.9-8.6a5.5 5.5 0 0 0-.1-7.8Z"/></svg>
    case 'operations': return <svg {...shared}><path d="M14.7 6.3a4 4 0 0 0-5 5L3 18l3 3 6.7-6.7a4 4 0 0 0 5-5l-3 3-2-2 2-4Z"/></svg>
    case 'assets': return <svg {...shared}><path d="m12 3 8 4.5-8 4.5-8-4.5L12 3ZM4 12l8 4.5 8-4.5M4 16.5 12 21l8-4.5"/></svg>
    default: return <svg {...shared}><circle cx="12" cy="12" r="8"/></svg>
  }
}
