import { useEffect, useState } from 'react'
import { api } from '../api'
import { Empty, Spinner } from '../views/ui'

export default function SpecialistQueue({ title }: { title: string }) {
  const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[selected,setSelected]=useState<string | null>(null)
  const load=()=>api.specialistQueue().then(setData).catch((e:any)=>setError(e.message))
  useEffect(() => { void load() }, [])
  async function act(item:any,status:string){
    try {
      setBusy(item.requirement_id)
      if (item.state === 'ROUTED') { await api.specialistAccept(item.requirement_id, { expected_version: item.version, reason: 'Accepted by specialist office' }); load(); return }
      if(!item.record_id) await api.createSpecialistRecord(item.requirement_id)
      await api.updateSpecialistRecord(item.requirement_id,{expected_version:item.version,status,notes:''}); load()
    } catch(e:any){setError(e.message)} finally{setBusy('')} }
  if(!data&&!error)return <Spinner />
  return <div className="fade-in"><div className="page-head"><h1>{title}</h1><p>Only work currently assigned to your office and scope is shown.</p></div>{error&&<div className="err-box">{error}</div>}<section className="card"><div className="tbl-scroll"><table className="tbl"><thead><tr><th>Reference</th><th>Requirement</th><th>Requester / scope</th><th>Priority</th><th>SLA</th><th>State</th><th /></tr></thead><tbody>{data?.items?.length?data.items.map((x:any)=><tr key={x.requirement_id} onClick={()=>setSelected(x.requirement_id)}><td className="mono">{x.reference}</td><td><button className="link-button" onClick={(event)=>{event.stopPropagation();setSelected(x.requirement_id)}}><b>{x.title}</b></button><small>{x.category}</small></td><td>{x.requester_id}<small>{x.school_id || 'School-wide'} · {x.department_id || 'Department-wide'}</small></td><td>{x.priority}</td><td>{x.due_at ? new Date(x.due_at).toLocaleDateString() : 'No due date'}</td><td><span className={`pill s-${String(x.state).toLowerCase()}`}>{x.state.replaceAll('_',' ')}</span></td><td>{x.state==='ROUTED'&&<button disabled={busy===x.requirement_id} className="btn btn-sm btn-teal" onClick={(event)=>{event.stopPropagation();act(x,'ACCEPT')}}>Accept</button>}{x.state==='IN_EXECUTION'&&<button disabled={busy===x.requirement_id} className="btn btn-sm btn-teal" onClick={(event)=>{event.stopPropagation();act(x,'IN_PROGRESS')}}>Start</button>}{x.state==='IN_PROGRESS'&&<><button disabled={busy===x.requirement_id} className="btn btn-sm btn-brass" onClick={(event)=>{event.stopPropagation();act(x,'ON_HOLD')}}>Hold</button><button disabled={busy===x.requirement_id} className="btn btn-sm btn-brass" onClick={(event)=>{event.stopPropagation();act(x,'COMPLETED')}}>Complete</button></>}{x.state==='ON_HOLD'&&<button disabled={busy===x.requirement_id} className="btn btn-sm btn-teal" onClick={(event)=>{event.stopPropagation();act(x,'IN_PROGRESS')}}>Resume</button>}</td></tr>):<tr><td colSpan={7}><Empty text="No specialist work is assigned to your current office."/></td></tr>}</tbody></table></div></section>{selected&&<SpecialistDetail id={selected} onClose={()=>setSelected(null)} />}</div>
}

function SpecialistDetail({ id, onClose }: { id: string; onClose: () => void }) {
  const [data,setData]=useState<any>(null),[error,setError]=useState('')
  useEffect(()=>{api.specialistDetail(id).then(setData).catch((e:any)=>setError(e.message || 'Unable to load specialist detail'))},[id])
  return <div className="modal-bg" onClick={onClose}><aside className="modal modal-wide administration-detail" onClick={event=>event.stopPropagation()}><div className="modal-h"><div><h3>{data?.requirement?.reference_code || 'Specialist detail'}</h3><span className="hint">Authorized execution workspace</span></div><button className="close-x" onClick={onClose}>×</button></div>{error?<div className="err-box">{error}</div>:!data?<Spinner/>:<div className="modal-b administration-detail-body"><section><h4>Requirement</h4><h2>{data.requirement.title}</h2><div className="detail-grid"><div><small>State</small><b>{data.requirement.state}</b></div><div><small>Category</small><b>{data.requirement.category}</b></div><div><small>Priority</small><b>{data.requirement.priority}</b></div><div><small>Due</small><b>{data.requirement.due_at ? new Date(data.requirement.due_at).toLocaleString() : 'No due date'}</b></div></div></section><section><h4>Specialist record</h4><pre className="detail-json">{JSON.stringify(data.record,null,2)}</pre></section><section><h4>Evidence readiness</h4><p className="hint">{data.evidence_policy?.satisfied ? 'Verified evidence is complete.' : `Missing: ${(data.evidence_policy?.missing || []).join(', ') || 'None'} · Pending: ${(data.evidence_policy?.pending_verification || []).join(', ') || 'None'}`}</p></section><section><h4>Execution history</h4>{data.history?.length ? data.history.map((item:any,index:number)=><div className="detail-history" key={`${item.at}-${index}`}><b>{item.from} → {item.to}</b><small>{item.actor_id} · {new Date(item.at).toLocaleString()} · {item.reason || 'No reason'}</small></div>):<Empty text="No execution history recorded."/>}</section></div>}<div className="modal-f"><button className="btn btn-out" onClick={onClose}>Close panel</button></div></aside></div>
}
