import { useEffect, useState } from 'react'
import { api } from '../api'
import { Empty, Modal, Spinner } from '../modules/kit'

const label = (value: string) => value.replace(/_/g, ' ').replace(/\b\w/g, part => part.toUpperCase())
const when = (value: string) => value ? new Date(value).toLocaleString() : '-'
const initial = { section_id: '', title: '', instructions: '', max_marks: 20, due_at: '', allow_late: true, action: 'draft' }

export function FacultyAssignments() {
  const [data, setData] = useState<any>(null), [home, setHome] = useState<any>(null), [form, setForm] = useState<any>(initial), [editing, setEditing] = useState<any>(null), [register, setRegister] = useState<any>(null), [evaluation, setEvaluation] = useState<any>(null), [message, setMessage] = useState(''), [saving, setSaving] = useState(false)
  const load = () => Promise.all([api.facultyAssignments(), api.facultyHome()]).then(([assignments, facultyHome]) => { setData(assignments); setHome(facultyHome) }).catch(() => setData({ error: true }))
  useEffect(() => { load() }, [])
  const openCreate = () => { setForm({ ...initial, section_id: home?.sections?.[0]?.id || '' }); setEditing('new'); setMessage('') }
  const openEdit = (row: any) => { setForm({ section_id: row.section_id, title: row.title, instructions: row.instructions, max_marks: row.max_marks, due_at: row.due_at ? row.due_at.slice(0, 16) : '', allow_late: row.allow_late, action: row.status === 'published' ? 'publish' : 'draft' }); setEditing(row); setMessage('') }
  const publishRow = async (row: any) => { setSaving(true); setMessage(''); try { await api.updateFacultyAssignment(row.id, { section_id: row.section_id, title: row.title, instructions: row.instructions, max_marks: row.max_marks, due_at: row.due_at, allow_late: row.allow_late, action: 'publish' }); load() } catch (error: any) { setMessage(error.message || 'Could not publish assignment.') } finally { setSaving(false) } }
  const save = async (action = form.action) => { setSaving(true); setMessage(''); try { const body = { ...form, action }; if (editing === 'new') await api.createFacultyAssignment(body); else await api.updateFacultyAssignment(editing.id, body); setEditing(null); load() } catch (error: any) { setMessage(error.message || 'Could not save assignment.') } finally { setSaving(false) } }
  const openRegister = async (row: any) => { try { setRegister(await api.facultyAssignmentSubmissions(row.id)) } catch (error: any) { setMessage(error.message || 'Could not load submissions.') } }
  const decide = async (action: string) => { if (!evaluation) return; setSaving(true); try { await api.evaluateAssignmentSubmission(evaluation.submission_id, { action, marks_awarded: evaluation.marks_awarded === '' ? null : Number(evaluation.marks_awarded), feedback: evaluation.feedback, internal_comment: evaluation.internal_comment || '' }); const id = register.assignment.id; setEvaluation(null); setRegister(await api.facultyAssignmentSubmissions(id)); load() } catch (error: any) { setMessage(error.message || 'Could not save evaluation.') } finally { setSaving(false) } }
  if (!data) return <Spinner />
  if (data.error) return <Empty icon="!" text="Assignments could not be loaded." />
  return <main className="assess-workspace fade-in"><section className="assess-heading"><h1>Assignments</h1><p>Create, publish, track submissions, and evaluate work for your active sections.</p></section><article className="assess-register"><header><h2>Assignment Register</h2><button onClick={openCreate} type="button">Create Assignment</button></header><div className="assess-table-wrap"><table className="assess-table"><thead><tr><th>Assignment</th><th>Course</th><th>Section</th><th>Due Date</th><th>Max Marks</th><th>Submitted</th><th>Evaluated</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.assignments.map((row: any) => <tr key={row.id}><td><b>{row.title}</b></td><td>{row.course_code}</td><td>{row.section}</td><td>{when(row.due_at)}</td><td>{row.max_marks}</td><td>{row.submitted}/{row.enrolled}</td><td>{row.evaluated}</td><td>{label(row.status)}</td><td><span className="row-actions">{row.status === 'draft' && <><button onClick={() => openEdit(row)} type="button">Edit</button><button disabled={saving} onClick={() => publishRow(row)} type="button">Publish</button></>}{row.status !== 'draft' && <button onClick={() => openRegister(row)} type="button">{row.status === 'published' ? 'View Submissions' : 'View'}</button>}</span></td></tr>)}{!data.assignments.length && <tr><td colSpan={9}>No assignments for your active sections.</td></tr>}</tbody></table></div></article>{message && <p className="att-message">{message}</p>}
    {editing && <Modal className="modal-wide" title={editing === 'new' ? 'Create Assignment' : 'Edit Assignment'} onClose={() => setEditing(null)} footer={<><button className="btn btn-out" onClick={() => setEditing(null)} type="button">Cancel</button><button className="btn btn-out" disabled={saving} onClick={() => save('draft')} type="button">Save Draft</button><button className="btn btn-crimson" disabled={saving} onClick={() => save('publish')} type="button">Publish</button></>}><div className="form-row"><label>Course / Section</label><select className="select" disabled={editing !== 'new'} value={form.section_id} onChange={event => setForm({ ...form, section_id: event.target.value })}>{(home?.sections || []).map((section: any) => <option key={section.id} value={section.id}>{section.course_code} - {section.title} / {section.section}</option>)}</select></div><div className="form-row"><label>Title</label><input className="inp" value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /></div><div className="form-row"><label>Instructions</label><textarea className="inp" value={form.instructions} onChange={event => setForm({ ...form, instructions: event.target.value })} /></div><div className="grid-2"><div className="form-row"><label>Maximum Marks</label><input className="inp" type="number" value={form.max_marks} onChange={event => setForm({ ...form, max_marks: Number(event.target.value) })} /></div><div className="form-row"><label>Due Date / Time</label><input className="inp" type="datetime-local" value={form.due_at} onChange={event => setForm({ ...form, due_at: event.target.value })} /></div></div><label><input type="checkbox" checked={form.allow_late} onChange={event => setForm({ ...form, allow_late: event.target.checked })} /> Allow late submission</label></Modal>}
    {register && <Modal className="modal-wide" title={`Submissions - ${register.assignment.title}`} onClose={() => setRegister(null)}><div className="marks-sheet-summary"><span>{register.assignment.course_code} {register.assignment.section}</span><span>{register.assignment.submitted}/{register.assignment.enrolled} submitted</span><span>{register.assignment.evaluated} evaluated</span></div><div className="marks-sheet-table"><table><thead><tr><th>Student</th><th>Submitted At</th><th>Status</th><th>Attempt</th><th>Marks</th><th>Action</th></tr></thead><tbody>{register.roster.map((row: any) => <tr key={row.student_id}><td><b>{row.roll_no}</b> {row.student}</td><td>{when(row.submitted_at)}</td><td>{row.late ? 'Late - ' : ''}{label(row.status)}</td><td>{row.attempt_no || '-'}</td><td>{row.marks_awarded ?? '-'}</td><td>{row.submission_id && <button onClick={() => setEvaluation({ ...row, marks_awarded: row.marks_awarded ?? '', feedback: row.feedback || '' })} type="button">{row.status === 'evaluated' ? 'View' : 'Evaluate'}</button>}</td></tr>)}</tbody></table></div></Modal>}
    {evaluation && <Modal title={`Evaluation - ${evaluation.student}`} onClose={() => setEvaluation(null)} footer={<><button className="btn btn-out" onClick={() => setEvaluation(null)} type="button">Close</button><button className="btn btn-out" disabled={saving} onClick={() => decide('return')} type="button">Return for Resubmission</button><button className="btn btn-crimson" disabled={saving} onClick={() => decide('evaluate')} type="button">Save Evaluation</button></>}><p><b>Submitted:</b> {when(evaluation.submitted_at)} {evaluation.late ? '(Late)' : '(On time)'} | Attempt {evaluation.attempt_no}</p><div className="form-row"><label>Submission</label><p>{evaluation.submission_text || 'No text submitted.'}</p></div><div className="form-row"><label>Marks</label><input className="inp" type="number" value={evaluation.marks_awarded} onChange={event => setEvaluation({ ...evaluation, marks_awarded: event.target.value })} /></div><div className="form-row"><label>Student Feedback</label><textarea className="inp" value={evaluation.feedback} onChange={event => setEvaluation({ ...evaluation, feedback: event.target.value })} /></div></Modal>}
  </main>
}

export function StudentAssignments() {
  const [data, setData] = useState<any>(null), [selected, setSelected] = useState<any>(null), [text, setText] = useState(''), [message, setMessage] = useState(''), [saving, setSaving] = useState(false)
  const load = () => api.studentAssignments().then(setData).catch(() => setData({ error: true }))
  useEffect(() => { load() }, [])
  const open = async (id: string) => { const response = await api.studentAssignment(id); setSelected(response.assignment); setText(response.assignment.submission_text || ''); setMessage('') }
  const submit = async () => { if (!selected || saving) return; setSaving(true); try { await api.submitStudentAssignment(selected.id, { submission_text: text }); await open(selected.id); load(); setMessage('Submission saved.') } catch (error: any) { setMessage(error.message || 'Could not submit assignment.') } finally { setSaving(false) } }
  const actionLabel = (row: any) => {
    if (row.submission_status === 'not_submitted') return 'Submit'
    if (row.submission_status === 'returned') return 'Resubmit'
    if (row.submission_status === 'evaluated') return 'View Result'
    return 'View Submission'
  }
  if (!data) return <Spinner />
  if (data.error) return <Empty icon="!" text="Assignments could not be loaded." />
  return <main className="assess-workspace fade-in"><section className="assess-heading"><h1>Assignments</h1><p>Submit work and review your own feedback and marks.</p></section><article className="assess-register"><div className="assess-table-wrap"><table className="assess-table"><thead><tr><th>Assignment</th><th>Course</th><th>Professor</th><th>Assigned Date</th><th>Due Date</th><th>Max Marks</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.assignments.map((row: any) => <tr key={row.id}><td><b>{row.title}</b></td><td><b>{row.course_code}</b><span>{row.course_title}{row.section ? ` Â· ${row.section}` : ''}</span></td><td>{row.professor || '-'}</td><td>{when(row.assigned_at)}</td><td>{when(row.due_at)}</td><td>{row.max_marks}</td><td>{label(row.submission_status)}</td><td><button onClick={() => open(row.id)} type="button">{actionLabel(row)}</button></td></tr>)}{!data.assignments.length && <tr><td colSpan={8}>No published assignments.</td></tr>}</tbody></table></div></article>{selected && <Modal className="modal-wide" title={selected.title} onClose={() => setSelected(null)} footer={<><button className="btn btn-out" onClick={() => setSelected(null)} type="button">Close</button>{selected.can_submit && <button className="btn btn-crimson" disabled={saving} onClick={submit} type="button">{saving ? 'Saving...' : (selected.submission_status === 'returned' ? 'Resubmit' : 'Submit')}</button>}</>}><p>{selected.instructions}</p><p><b>Professor:</b> {selected.professor || '-'} | <b>Due:</b> {when(selected.due_at)} | <b>Maximum marks:</b> {selected.max_marks}</p>{selected.feedback && <p className="marks-draft-message">Feedback: {selected.feedback}</p>}{selected.can_submit ? <div className="form-row"><label>Submission text</label><textarea className="inp" value={text} onChange={event => setText(event.target.value)} /></div> : <><p><b>Submission:</b> {selected.submission_text}</p>{selected.submission_status === 'evaluated' && <p><b>Result:</b> {selected.marks_awarded}/{selected.max_marks}</p>}</>}{message && <p className="att-message">{message}</p>}</Modal>}</main>
}


