import { useEffect, useState } from 'react'
import { api } from '../api'
import { Spinner } from '../modules/kit'

export default function AssociateProfessorHome({ go }: { go: (view: string) => void }) {
  const [home, setHome] = useState<any>(null)
  useEffect(() => { api.facultyHome().then(setHome).catch(() => setHome({ error: true })) }, [])
  if (!home) return <Spinner />
  if (home.error) return <div className="empty">Associate Professor overview could not be loaded.</div>
  const k = home.kpis || {}, sections = home.sections || [], schedule = home.teaching_schedule || [], pending = home.pending_tasks || []
  const context = home.associate_context || {}, today = new Date().toISOString().slice(0, 10)
  const classes = schedule.filter((row: any) => row.date === today), lowAttendance = sections.filter((row: any) => row.attendance_pct != null && row.attendance_pct < 75).length
  const cards = [['▤', context.assigned_courses ?? 0, 'Assigned Courses', 'academics'], ['▱', sections.length, 'Assigned Sections', 'academics'], ['♧', k.students ?? 0, 'Students Mapped', 'students'], ['▣', k.classes_this_week ?? 0, 'Classes This Week', 'my_schedule'], ['☑', lowAttendance, 'Attendance Pending', 'attendance'], ['✎', k.marks_entry_pending ?? 0, 'Marks Pending', 'assessments']]
  return <main className="associate-home fade-in">
    <header className="associate-heading"><div><h1>Welcome, Associate Professor</h1><p>Mid-senior faculty responsible for assigned teaching, coordination, and student advising.</p></div><button onClick={() => go('my_schedule')} type="button">▣ &nbsp; View Full Schedule</button></header>
    <section className="associate-kpis">{cards.map(([icon, value, label, route]) => <button key={String(label)} onClick={() => go(String(route))} type="button"><i>{icon}</i><span><b>{value}</b><small>{label}</small><em>View details</em></span></button>)}</section>
    <section className="associate-grid top"><article><header><h2>▣ &nbsp; Today’s Schedule</h2><button onClick={() => go('my_schedule')} type="button">View full schedule</button></header>{classes.slice(0,4).map((row: any) => <div className="associate-schedule" key={row.id}><b>{row.time}</b><strong>{row.course_code}</strong><span>{row.subject}</span><em>{row.section}</em></div>)}{!classes.length && <p className="associate-empty">No classes scheduled for today.</p>}</article><article><header><h2>♧ &nbsp; Teaching Alerts</h2></header><ul className="associate-alerts"><li>{lowAttendance} section(s) have low attendance (&lt;75%)</li><li>{pending.length} academic task(s) require attention</li><li>{k.marks_entry_pending ?? 0} marks submissions due</li><li>0 attendance review requests pending</li></ul></article><article className="associate-courses"><header><h2>▤ &nbsp; My Courses &amp; Sections</h2><button onClick={() => go('academics')} type="button">View all →</button></header><table><thead><tr><th>Course</th><th>Section</th><th>Students</th><th>Attendance</th><th /></tr></thead><tbody>{sections.slice(0,5).map((row: any) => <tr key={row.id}><td><b>{row.course_code}</b><small>{row.title}</small></td><td>{row.section}</td><td>{row.enrolled || 0}</td><td>{row.attendance_pct == null ? '—' : `${Math.round(row.attendance_pct)}%`}</td><td><button onClick={() => go('academics')} type="button">Open</button></td></tr>)}</tbody></table></article></section>
    <section className="associate-grid bottom"><article><header><h2>⚑ &nbsp; Needs My Attention</h2></header><ul className="associate-alerts"><li>Attendance pending <b>{lowAttendance}</b></li><li>Marks moderation review <b>{k.marks_entry_pending ?? 0}</b></li><li>Academic tasks <b>{pending.length}</b></li><li>At-risk advisees <b>{context.at_risk_advisees ?? 0}</b></li></ul></article>{context.coordination && <article><header><h2>▱ &nbsp; Course Coordination</h2></header><ul className="associate-alerts"><li>Assigned coordination scope <b>Active</b></li><li>Sections covered <b>{sections.length}</b></li><li>Pending reports <b>0</b></li></ul></article>}<article><header><h2>▣ &nbsp; My Advisees / Academic Risk</h2><button onClick={() => go('mentoring')} type="button">View all →</button></header><div className="associate-advisee"><span><b>{context.advisees ?? 0}</b>Advisees</span><span><b>{context.at_risk_advisees ?? 0}</b>At-risk</span></div>{(context.advisee_preview || []).slice(0,2).map((row: any) => <p className="associate-person" key={row.id}><b>{row.name}</b><span>{row.risk === 'attention' ? 'Needs attention' : 'On track'}</span></p>)}</article><article><header><h2>Assessments &amp; Marks Summary</h2></header><div className="associate-summary"><b>{home.performance?.assessments ?? 0}</b><span>Total assessments</span><b>{home.performance?.marks_entered ?? 0}</b><span>Marks entered</span></div><button className="associate-link" onClick={() => go('assessments')} type="button">View all assessments →</button></article></section>
    <article className="associate-actions"><h2>ϟ &nbsp; Quick Actions</h2>{[['Mark Attendance','attendance'],['Create Assignment','academics'],['Create Assessment','assessments'],['Enter Marks','marks_entry'],['Upload Materials','course_materials']].map(([label,route]) => <button key={label} onClick={() => go(route)} type="button">{label}</button>)}</article>
  </main>
}
