import { useEffect, useState } from 'react'
import { api } from '../api'
import { Empty, Spinner } from '../modules/kit'

const display = (value: any) => value || '—'

export default function FacultyProfile() {
  const [data, setData] = useState<any>(null), [editing, setEditing] = useState(false), [draft, setDraft] = useState<any>({}), [saving, setSaving] = useState(false), [message, setMessage] = useState('')
  const load = async () => { try { const next = await api.facultySelfProfile(); setData(next); setDraft(next.profile) } catch { setData({ error: true }) } }
  useEffect(() => { load() }, [])
  if (!data) return <Spinner />
  if (data.error) return <Empty icon="!" text="Your profile could not be loaded." />
  const profile = data.profile, initials = profile.name.split(' ').map((part: string) => part[0]).slice(0, 2).join('')
  const save = async () => { setSaving(true); setMessage(''); try { await api.updateFacultySelfProfile({ email: draft.email || '', phone: draft.phone || '', office_hours: draft.office_hours || '' }); await load(); setEditing(false); setMessage('Profile updated.') } catch (error: any) { setMessage(error.message || 'Could not update your profile.') } finally { setSaving(false) } }
  const cancel = () => { setDraft(profile); setEditing(false); setMessage('') }
  return <main className="faculty-profile-page fade-in"><section className="faculty-hero faculty-profile-hero"><div className="faculty-hero-avatar">{initials}</div><div className="faculty-identity"><h1>{profile.name}</h1><p>{display(profile.designation)} · {display(profile.department)}</p><span>{display(profile.campus)} · Faculty ID {display(profile.employee_id)}</span></div><button type="button" onClick={() => setEditing(true)} disabled={editing}>Edit Profile</button></section>{message && <p className="att-message">{message}</p>}
    <section className="faculty-profile-grid"><Info title="Personal Information" rows={[["Full name", profile.name], ["Employee ID", profile.employee_id], ["Gender", null], ["Date of birth", null]]}/><section className="faculty-card faculty-profile-card"><header><h2>Contact Information</h2>{editing && <span>Editable</span>}</header><div className="faculty-profile-fields"><Field label="Email" value={draft.email} readOnly={!editing} onChange={(value: string) => setDraft({ ...draft, email: value })}/><Field label="Phone" value={draft.phone} readOnly={!editing} onChange={(value: string) => setDraft({ ...draft, phone: value })}/><Read label="Alternate contact" value={null}/><Read label="Address" value={null}/></div></section><Info title="Employment Information" rows={[["Designation", profile.designation], ["Department", profile.department], ["Campus", profile.campus], ["Joining date", profile.date_joined], ["Employment status", profile.employment_status], ["Reporting authority", null]]}/><section className="faculty-card faculty-profile-card"><header><h2>Academic / Professional Information</h2>{editing && <span>Office hours editable</span>}</header><div className="faculty-profile-fields"><Read label="Highest qualification" value={null}/><Read label="Specialization" value={null}/><Read label="Experience" value={null}/><Read label="Office location" value={null}/><Field label="Office hours" value={draft.office_hours} readOnly={!editing} onChange={(value: string) => setDraft({ ...draft, office_hours: value })}/><Read label="Research interests / bio" value={null}/></div></section><section className="faculty-card faculty-profile-card faculty-profile-wide"><header><h2>Account / Responsibilities</h2></header><div className="faculty-profile-fields"><Read label="Username" value={profile.username}/><Read label="Base role" value={profile.base_role}/><div className="faculty-profile-row"><span>Active responsibilities</span><div>{data.assignments.length ? data.assignments.map((item: any, index: number) => <p key={index}>{item.role}{item.scope ? ` – ${item.scope}` : ''}</p>) : <b>—</b>}</div></div></div></section></section>{editing && <footer className="faculty-profile-actions"><button type="button" onClick={cancel} disabled={saving}>Cancel</button><button type="button" onClick={save} disabled={saving}>{saving ? 'Saving…' : 'Save changes'}</button></footer>}</main>
}

function Info({ title, rows }: any) { return <section className="faculty-card faculty-profile-card"><header><h2>{title}</h2></header><div className="faculty-profile-fields">{rows.map(([label, value]: any) => <Read key={label} label={label} value={value}/>)}</div></section> }
function Read({ label, value }: any) { return <div className="faculty-profile-row"><span>{label}</span><b>{display(value)}</b></div> }
function Field({ label, value, readOnly, onChange }: any) { return <label className="faculty-profile-row"><span>{label}</span>{readOnly ? <b>{display(value)}</b> : <input value={value || ''} onChange={event => onChange(event.target.value)} />}</label> }
