import { useEffect, useState } from 'react'
import { api } from '../api'
import { Empty, Modal, Spinner } from '../modules/kit'

const blank = { category: 'Academic Performance', risk_level: 'low', summary: '', action_plan: '', follow_up_date: '' }
const categories = ['Attendance', 'Academic Performance', 'Backlogs', 'Behaviour/Discipline', 'Personal/Wellbeing', 'Career/Placement', 'Other']
const title = (value: string) => (value || '').replace(/_/g, ' ').replace(/\b\w/g, item => item.toUpperCase())

export default function FacultyMentoring() {
  const [data, setData] = useState<any>(null), [query, setQuery] = useState(''), [student, setStudent] = useState<any>(null), [caseItem, setCaseItem] = useState<any>(null), [createFor, setCreateFor] = useState<any>(null), [form, setForm] = useState(blank), [note, setNote] = useState(''), [saving, setSaving] = useState(false), [message, setMessage] = useState('')
  const load = async () => { try { const [mentees, cases] = await Promise.all([api.facultyMentees(), api.mentoringCases()]); setData({ mentees: mentees.mentees || [], cases: cases.cases || [] }) } catch { setData({ error: true }) } }
  useEffect(() => { load() }, [])
  const openStudent = async (item: any) => { try { setStudent(await api.facultyMentee(item.id)) } catch (error: any) { setMessage(error.message) } }
  const openCase = async (id: string) => { try { const result = await api.mentoringCase(id); setCaseItem(result.case) } catch (error: any) { setMessage(error.message) } }
  const run = async (work: () => Promise<any>) => { setSaving(true); setMessage(''); try { await work(); await load() } catch (error: any) { setMessage(error.message || 'Could not update mentoring case.') } finally { setSaving(false) } }
  const createCase = () => run(async () => { const result = await api.createMentoringCase(createFor.id, form); setCreateFor(null); setForm(blank); await openCase(result.case.id) })
  const addNote = () => run(async () => { await api.addMentoringNote(caseItem.id, { content: note }); setNote(''); await openCase(caseItem.id) })
  const savePlan = () => run(async () => { await api.updateMentoringCase(caseItem.id, { action_plan: caseItem.action_plan, follow_up_date: caseItem.follow_up_date }); await openCase(caseItem.id) })
  const closeCase = (action: 'resolve' | 'close') => run(async () => { await api.closeMentoringCase(caseItem.id, action); await openCase(caseItem.id) })
  if (!data) return <Spinner />
  if (data.error) return <Empty icon="!" text="Your assigned advisees could not be loaded." />
  const mentees = data.mentees.filter((item: any) => !query.trim() || `${item.name} ${item.roll_no} ${item.department}`.toLowerCase().includes(query.toLowerCase()))
  const casesFor = (id: string) => data.cases.filter((item: any) => item.student_id === id && ['open', 'referred'].includes(item.status))
  return <main className="faculty-students fade-in"><section className="faculty-students-heading"><div><h1>Mentoring &amp; Advisees</h1><p>Manage support cases for students formally assigned to you.</p></div><span>{mentees.length} advisees</span></section><section className="faculty-student-filters mentoring-search"><label className="faculty-student-search">Search advisees<input value={query} onChange={event => setQuery(event.target.value)} placeholder="Name, roll number, or department" /></label></section><article className="faculty-student-table-card"><header><div><h2>My Advisees</h2><p>Risk indicators are current academic signals.</p></div><span>{data.cases.filter((item: any) => ['open', 'referred'].includes(item.status)).length} active cases</span></header><div className="faculty-student-table-wrap"><table><thead><tr><th>Student</th><th>Roll No.</th><th>Program / Section</th><th>Attendance</th><th>CGPA</th><th>Backlogs</th><th>Active Cases</th><th>Action</th></tr></thead><tbody>{mentees.map((item: any) => <tr key={item.id}><td><b>{item.name}</b></td><td>{item.roll_no}</td><td>{item.program || item.department} / {item.section || '-'}</td><td>{item.attendance_pct == null ? '-' : `${item.attendance_pct}%`}</td><td>{Number(item.cgpa || 0).toFixed(2)}</td><td>{item.backlogs || 0}</td><td>{casesFor(item.id).length}</td><td><span className="row-actions"><button onClick={() => openStudent(item)} type="button">View Progress</button><button onClick={() => { setCreateFor(item); setForm(blank) }} type="button">Create Case</button></span></td></tr>)}{!mentees.length && <tr><td colSpan={8}>No advisees match your search.</td></tr>}</tbody></table></div></article>{message && <p className="att-message">{message}</p>}
    {student && <Modal className="modal-wide" title={`Advisee Progress - ${student.student.name}`} onClose={() => setStudent(null)} footer={<button className="btn btn-out" onClick={() => setStudent(null)} type="button">Close</button>}><div className="grid-3"><div className="snap"><span>Attendance</span><b>{student.student.attendance_pct == null ? '-' : `${student.student.attendance_pct}%`}</b></div><div className="snap"><span>CGPA</span><b>{Number(student.student.cgpa || 0).toFixed(2)}</b></div><div className="snap"><span>Backlogs</span><b>{student.student.backlogs || 0}</b></div></div><h3>Recent assessments</h3>{student.marks_progress?.map((mark: any, index: number) => <p key={index}>{mark.assessment}: {mark.score} / {mark.max_marks} ({mark.status})</p>)}</Modal>}
    {createFor && <Modal title={`Open Mentoring Case - ${createFor.name}`} onClose={() => setCreateFor(null)} footer={<><button className="btn btn-out" onClick={() => setCreateFor(null)} type="button">Cancel</button><button className="btn btn-crimson" disabled={saving} onClick={createCase} type="button">Create Case</button></>}><div className="form-row"><label>Category</label><select className="select" value={form.category} onChange={event => setForm({ ...form, category: event.target.value })}>{categories.map(item => <option key={item}>{item}</option>)}</select></div><div className="form-row"><label>Risk Level</label><select className="select" value={form.risk_level} onChange={event => setForm({ ...form, risk_level: event.target.value })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></div><div className="form-row"><label>Concern / Summary</label><textarea className="inp" value={form.summary} onChange={event => setForm({ ...form, summary: event.target.value })} /></div><div className="form-row"><label>Action Plan</label><textarea className="inp" value={form.action_plan} onChange={event => setForm({ ...form, action_plan: event.target.value })} /></div></Modal>}
    {caseItem && <Modal className="modal-wide" title={`Mentoring Case - ${caseItem.student.name}`} onClose={() => setCaseItem(null)} footer={<button className="btn btn-out" onClick={() => setCaseItem(null)} type="button">Close</button>}><div className="marks-sheet-summary"><span>{caseItem.category}</span><span>{title(caseItem.risk_level)} risk</span><span>{title(caseItem.status)}</span></div><p>{caseItem.summary}</p><label>Action Plan<textarea className="inp" value={caseItem.action_plan || ''} onChange={event => setCaseItem({ ...caseItem, action_plan: event.target.value })} /></label><label>Follow-up Date<input className="inp" type="date" value={caseItem.follow_up_date || ''} onChange={event => setCaseItem({ ...caseItem, follow_up_date: event.target.value })} /></label><div className="row-actions"><button disabled={saving} onClick={savePlan} type="button">Save Plan</button><button disabled={saving} onClick={() => closeCase('resolve')} type="button">Resolve</button><button disabled={saving} onClick={() => closeCase('close')} type="button">Close Case</button></div><label>Add Note<textarea className="inp" value={note} onChange={event => setNote(event.target.value)} /></label><button disabled={saving || !note.trim()} onClick={addNote} type="button">Add Note</button></Modal>}
  </main>
}
