import { useEffect, useState } from 'react'
import { api } from '../api'
import { Empty, Modal, Spinner } from '../modules/kit'

const labels: any = { attendance: 'Attendance', academic: 'Academic', backlog: 'Backlog', assessment: 'Assessment' }
const show = (value: any) => value === null || value === undefined || value === '' ? '—' : value

export default function HodAtRiskStudents({ go }: { go: (view: string) => void }) {
  const [data, setData] = useState<any>(null)
  const [error, setError] = useState('')
  const [selected, setSelected] = useState<any>(null)
  const [filters, setFilters] = useState({ q: '', program: '', semester: '', section: '', risk: 'all', referral: 'all' })
  const load = async () => { setError(''); try { setData(await api.hodAtRiskStudents()) } catch (err: any) { setError(err.message || 'At-risk students could not be loaded.') } }
  useEffect(() => { load() }, [])
  if (error && !data) return <Empty icon="!" text={error} />
  if (!data) return <Spinner />

  const all = data.students || []
  const programs = [...new Map(all.map((row: any) => [row.program_id, row.program])).entries()].filter(([id]: any) => id)
  const semesters = [...new Set(all.map((row: any) => row.semester).filter(Boolean))].sort((a: any, b: any) => Number(a) - Number(b))
  const sections = [...new Set(all.map((row: any) => row.section).filter(Boolean))].sort()
  const visible = all.filter((row: any) => `${row.name} ${row.roll_no}`.toLowerCase().includes(filters.q.toLowerCase()) && (!filters.program || row.program_id === filters.program) && (!filters.semester || String(row.semester) === filters.semester) && (!filters.section || row.section === filters.section) && (filters.risk === 'all' || row.risk_codes?.includes(filters.risk)) && (filters.referral === 'all' || (filters.referral === 'referred' ? Boolean(row.mentoring_referral) : !row.mentoring_referral))).sort((a: any, b: any) => (b.risk_codes?.length || 0) - (a.risk_codes?.length || 0) || a.name.localeCompare(b.name))
  const count = (code: string) => all.filter((row: any) => row.risk_codes?.includes(code)).length
  const multiple = all.filter((row: any) => (row.risk_codes?.length || 0) > 1).length
  const referrals = all.filter((row: any) => row.mentoring_referral).length
  const grouped = Object.entries(all.reduce((items: any, row: any) => {
    const key = `${row.semester || '—'}|${row.section || '—'}`
    if (!items[key]) items[key] = { key, semester: row.semester, section: row.section, students: 0, attendance: 0, academic: 0, backlog: 0, assessment: 0, multiple: 0 }
    items[key].students += 1
    row.risk_codes.forEach((code: string) => { if (code in items[key]) items[key][code] += 1 })
    if (row.risk_codes.length > 1) items[key].multiple += 1
    return items
  }, {})).sort((a: any, b: any) => Number(a.semester || 0) - Number(b.semester || 0) || String(a.section).localeCompare(String(b.section)))
  const clear = () => setFilters({ q: '', program: '', semester: '', section: '', risk: 'all', referral: 'all' })

  return <main className="hod-risk-page fade-in">
    <header className="hod-risk-heading"><div><p>Department student monitoring</p><h1>At-Risk Students</h1><span>{data.department?.name || 'Your department'}{data.department?.code ? ` · ${data.department.code}` : ''} · Derived signals only; no intervention workflow is configured here.</span></div><button className="btn btn-out" onClick={load} type="button">Refresh data</button></header>
    {error && <p className="hod-risk-message" role="alert">{error}</p>}
    <section className="hod-risk-summary" aria-label="Risk summary"><Stat value={all.length} label="At-Risk Students" helper="One or more current signals" tone="risk" /><Stat value={count('attendance')} label="Attendance Risk" helper="Attendance below 75%" /><Stat value={count('academic')} label="Academic Risk" helper="CGPA below 6.50" /><Stat value={count('backlog')} label="Published Backlogs" helper="Latest subject outcome failed" /><Stat value={count('assessment')} label="Assessment Risk" helper="Published average below 50%" /><Stat value={multiple} label="Multiple Risks" helper="More than one signal" tone="attention" /></section>
    <section className="hod-risk-guidance"><div><p>Monitoring boundary</p><h2>Review risk indicators, then use the existing operational workspaces.</h2><span>No special-class approval, intervention request, or remedial scheduling action is available on this page.</span></div><div><button type="button" onClick={() => go('hod_attendance')}>Attendance Monitoring →</button><button type="button" onClick={() => go('hod_students')}>Department Students →</button><button type="button" onClick={() => go('hod_reviews_mentoring_referrals')}>Mentoring inbox ({referrals}) →</button></div></section>
    <section className="hod-risk-filters" aria-label="Risk filters"><label>Search<input value={filters.q} onChange={e => setFilters({ ...filters, q: e.target.value })} placeholder="Name or roll number" /></label><label>Program<select value={filters.program} onChange={e => setFilters({ ...filters, program: e.target.value })}><option value="">All programs</option>{programs.map(([id, name]: any) => <option value={id} key={id}>{name}</option>)}</select></label><label>Semester<select value={filters.semester} onChange={e => setFilters({ ...filters, semester: e.target.value })}><option value="">All semesters</option>{semesters.map((semester: any) => <option value={String(semester)} key={semester}>Semester {semester}</option>)}</select></label><label>Section<select value={filters.section} onChange={e => setFilters({ ...filters, section: e.target.value })}><option value="">All sections</option>{sections.map((section: any) => <option value={section} key={section}>{section}</option>)}</select></label><label>Risk category<select value={filters.risk} onChange={e => setFilters({ ...filters, risk: e.target.value })}><option value="all">All risk categories</option>{Object.entries(labels).map(([key, label]: any) => <option value={key} key={key}>{label}</option>)}</select></label><label>Mentoring referral<select value={filters.referral} onChange={e => setFilters({ ...filters, referral: e.target.value })}><option value="all">All students</option><option value="referred">Referred to HOD</option><option value="not_referred">No current referral</option></select></label><button className="btn btn-out" onClick={clear} type="button">Clear filters</button></section>
    <section className="hod-risk-overview" aria-label="Academic risk grouping"><header><div><p>Risk distribution</p><h2>Derived risk by semester and section</h2></div><span>Counts are grouped from the same HOD at-risk response.</span></header><div className="hod-risk-overview-table"><div className="hod-risk-overview-row labels"><span>Semester</span><span>Section</span><span>Students</span><span>Attendance</span><span>Academic</span><span>Backlog</span><span>Assessment</span><span>Multiple</span></div>{grouped.map((group: any) => <div className="hod-risk-overview-row" key={group.key}><span>Semester {show(group.semester)}</span><span>{show(group.section)}</span><span>{group.students}</span><span>{group.attendance}</span><span>{group.academic}</span><span>{group.backlog}</span><span>{group.assessment}</span><span>{group.multiple}</span></div>)}</div></section>
    <section className="hod-risk-register" aria-label="At-risk student register"><header><div><p>At-risk register</p><h2>{visible.length} visible student{visible.length === 1 ? '' : 's'}</h2></div><span>Mentoring metadata is limited to current HOD referral state.</span></header><div className="hod-risk-list">{visible.map((row: any) => <article className="hod-risk-card" key={row.id}><button className="hod-risk-main" onClick={() => setSelected(row)} type="button"><div className="hod-risk-ident"><b>{row.roll_no}</b><h3>{row.name}</h3><span>{row.program} · Semester {row.semester} · Section {row.section}</span></div><Metric label="CGPA" value={show(row.cgpa)} /><Metric label="Attendance" value={row.attendance_pct == null ? '—' : `${row.attendance_pct}%`} /><Metric label="Backlogs" value={row.backlog_count} /><Metric label="Assessment" value={row.assessment_average == null ? '—' : `${row.assessment_average}%`} /><div className="hod-risk-badges">{row.risk_codes.map((code: string) => <span key={code} className={code}>{labels[code]}</span>)}</div><Referral row={row} /></button><div className="hod-risk-actions"><button onClick={() => setSelected(row)} type="button">View safe detail</button><button onClick={() => go('hod_attendance')} type="button">Attendance</button><button onClick={() => go('hod_students')} type="button">Student record</button>{row.mentoring_referral && <button onClick={() => go('hod_reviews_mentoring_referrals')} type="button">Mentoring inbox</button>}</div></article>)}{!visible.length && <Empty icon="○" text="No at-risk students match the selected filters." />}</div></section>
    {selected && <RiskDetail row={selected} onClose={() => setSelected(null)} go={go} />}
  </main>
}

function Stat({ value, label, helper, tone = '' }: any) { return <article className={tone}><b>{value}</b><span>{label}</span><small>{helper}</small></article> }
function Metric({ label, value }: any) { return <div className="hod-risk-metric"><span>{label}</span><b>{value}</b></div> }
function Referral({ row }: any) { return row.mentoring_referral ? <span className="hod-risk-referral">Referred to HOD</span> : <span className="hod-risk-referral neutral">No current referral</span> }
function RiskDetail({ row, onClose, go }: any) { return <Modal className="modal-wide" title={`${row.name} · ${row.roll_no}`} onClose={onClose} footer={<><button className="btn btn-out" onClick={onClose} type="button">Close</button><button className="btn btn-out" onClick={() => go('hod_attendance')} type="button">Attendance Monitoring</button>{row.mentoring_referral && <button className="btn btn-crimson" onClick={() => go('hod_reviews_mentoring_referrals')} type="button">Mentoring Inbox</button>}</>}><section className="hod-risk-detail"><div className="hod-risk-detail-info"><span>Program / placement</span><b>{row.program} · Semester {row.semester} · Section {row.section}</b><span>CGPA</span><b>{show(row.cgpa)}</b><span>Attendance</span><b>{row.attendance_pct == null ? 'No calculable attendance' : `${row.attendance_pct}%`}</b><span>Published backlogs</span><b>{row.backlog_count}</b>{row.assessment_average != null && <><span>Published assessment average</span><b>{row.assessment_average}%</b></>}<span>Mentoring referral</span><b>{row.mentoring_referral ? 'Currently referred to HOD' : 'No current HOD referral'}</b></div><h3>Current risk reasons</h3><div className="hod-risk-badges detail">{row.risk_codes.map((code: string, index: number) => <span key={code} className={code}>{row.risk_reasons[index]}</span>)}</div><p className="hod-risk-detail-note">This view intentionally excludes mentoring summaries, notes, follow-ups, and intervention narratives.</p></section></Modal> }
