import { useEffect, useState } from 'react'
import { api } from '../api'
import { Empty, Modal, Spinner } from '../modules/kit'

const value = (input: any) => input === null || input === undefined || input === '' ? '—' : input
const pct = (part: number, total: number) => total ? Math.round((part / total) * 100) : 0

export default function HodAttendanceMonitoring({ go }: { go: (view: string) => void }) {
  const [data, setData] = useState<any>(null)
  const [error, setError] = useState('')
  const [selected, setSelected] = useState<any>(null)
  const [filters, setFilters] = useState({ q: '', course: '', section: '', faculty: '', state: 'all', risk: 'all' })
  const load = async () => {
    setError('')
    try {
      const [monitoring, reviews, atRisk] = await Promise.all([api.hodAttendanceMonitoring(), api.hodReviews('attendance_corrections'), api.hodAtRiskStudents()])
      setData({ sections: monitoring.sections || [], sessions: monitoring.sessions || [], students: monitoring.students || [], department: monitoring.department || null, corrections: reviews.counts?.attendance_corrections_pending || 0, atRisk: atRisk.students || [] })
    } catch (err: any) { setError(err.message || 'Attendance monitoring could not be loaded.') }
  }
  useEffect(() => { load() }, [])
  if (error && !data) return <Empty icon="!" text={error} />
  if (!data) return <Spinner />

  const courses = [...new Set(data.sections.map((row: any) => row.course_code).filter(Boolean))].sort()
  const sections = [...new Set(data.sections.map((row: any) => row.section).filter(Boolean))].sort()
  const faculty = [...new Set(data.sections.map((row: any) => row.faculty).filter((name: string) => name && name !== 'Not assigned'))].sort()
  const riskByStudent = data.atRisk.filter((row: any) => row.risk_codes?.includes('attendance'))
  const belowThreshold = data.students.filter((row: any) => row.attendance_pct !== null && row.attendance_pct < 75).sort((a: any, b: any) => Number(a.attendance_pct) - Number(b.attendance_pct))
  const visible = data.sections.filter((row: any) => `${row.course_code} ${row.course_title} ${row.section}`.toLowerCase().includes(filters.q.toLowerCase()) && (!filters.course || row.course_code === filters.course) && (!filters.section || row.section === filters.section) && (!filters.faculty || row.faculty === filters.faculty) && (filters.state === 'all' || (filters.state === 'finalized' ? row.attendance_pending === 0 && row.attendance_finalized > 0 : filters.state === 'pending' ? row.attendance_pending > 0 : row.attendance_finalized === 0)) && (filters.risk === 'all' || (filters.risk === 'below_75' ? row.attendance_pct !== null && row.attendance_pct < 75 : row.attendance_pct !== null && row.attendance_pct >= 75)))
  const totalSessions = data.sessions.length
  const finalized = data.sessions.filter((row: any) => row.finalized).length
  const pending = data.sessions.filter((row: any) => row.checked_in && !row.finalized).length
  const finalizedRecords = data.sections.reduce((sum: number, row: any) => sum + Number(row.finalized_record_count || 0), 0)
  const weightedAttendance = finalizedRecords ? Math.round(data.sections.reduce((sum: number, row: any) => sum + (Number(row.attendance_pct || 0) * Number(row.finalized_record_count || 0)), 0) / finalizedRecords * 10) / 10 : null
  const health = { high: data.students.filter((row: any) => row.attendance_pct !== null && row.attendance_pct >= 90).length, watch: data.students.filter((row: any) => row.attendance_pct !== null && row.attendance_pct >= 75 && row.attendance_pct < 90).length, risk: data.students.filter((row: any) => row.attendance_pct !== null && row.attendance_pct < 75).length, unavailable: data.students.filter((row: any) => row.attendance_pct === null).length }
  const sessionRows = data.sessions.filter((row: any) => `${row.course_code} ${row.section} ${row.faculty}`.toLowerCase().includes(filters.q.toLowerCase()) && (!filters.course || row.course_code === filters.course) && (!filters.section || row.section === filters.section) && (!filters.faculty || row.faculty === filters.faculty) && (filters.state === 'all' || (filters.state === 'finalized' ? row.finalized : filters.state === 'pending' ? row.checked_in && !row.finalized : !row.finalized && !row.checked_in)))
  const clear = () => setFilters({ q: '', course: '', section: '', faculty: '', state: 'all', risk: 'all' })

  return <main className="hod-attendance-page fade-in">
    <header className="hod-attendance-heading"><div><p>Department attendance oversight</p><h1>Attendance Monitoring</h1><span>{data.department?.name || 'Your department'}{data.department?.code ? ` · ${data.department.code}` : ''} · Shared session and finalized attendance records.</span></div><button className="btn btn-out" onClick={load} type="button">Refresh data</button></header>
    {error && <p className="hod-attendance-message" role="alert">{error}</p>}
    <section className="hod-attendance-summary" aria-label="Attendance summary"><Stat value={totalSessions} label="Total Sessions" helper="Persisted class sessions" /><Stat value={finalized} label="Finalized Sessions" helper="Session finalization field" /><Stat value={pending} label="Pending Finalization" helper="Checked in, not finalized" tone="attention" /><Stat value={weightedAttendance == null ? '—' : `${weightedAttendance}%`} label="Department Attendance" helper="Finalized records only" /><Stat value={riskByStudent.length} label="Below 75%" helper="Existing risk calculation" tone="risk" /><Stat value={data.corrections} label="Corrections Awaiting HOD" helper="Existing review inbox" tone="attention" /></section>
    <section className="hod-attendance-readiness"><div><p>Attendance finalization</p><h2>{finalized} of {totalSessions} sessions finalized</h2><span>Only `ClassSession.finalized_at` determines finalized status.</span></div><div className="hod-attendance-progress"><b>{pct(finalized, totalSessions)}%</b><i><span style={{ width: `${pct(finalized, totalSessions)}%` }} /></i><small>{pending} checked-in session{pending === 1 ? '' : 's'} still pending finalization</small></div><div className="hod-attendance-review"><span>Correction workflow</span><b>{data.corrections}</b><button type="button" onClick={() => go('hod_reviews_attendance_corrections')}>Review corrections →</button></div></section>
    <section className="hod-attendance-health" aria-label="Attendance health"><header><div><p>Attendance health</p><h2>Existing at-risk student distribution</h2></div><span>Counts use the current HOD at-risk endpoint; no local risk formula.</span></header><div><Health value={health.high} label="90% and above" tone="good" /><Health value={health.watch} label="75% to 89.9%" tone="watch" /><Health value={health.risk} label="Below 75%" tone="risk" /><Health value={health.unavailable} label="No attendance data" tone="muted" /></div></section>
    <section className="hod-attendance-filters" aria-label="Attendance filters"><label>Search<input value={filters.q} onChange={e => setFilters({ ...filters, q: e.target.value })} placeholder="Course, section, or faculty" /></label><label>Course<select value={filters.course} onChange={e => setFilters({ ...filters, course: e.target.value })}><option value="">All courses</option>{courses.map((course: string) => <option value={course} key={course}>{course}</option>)}</select></label><label>Section<select value={filters.section} onChange={e => setFilters({ ...filters, section: e.target.value })}><option value="">All sections</option>{sections.map((section: string) => <option value={section} key={section}>{section}</option>)}</select></label><label>Faculty<select value={filters.faculty} onChange={e => setFilters({ ...filters, faculty: e.target.value })}><option value="">All assigned faculty</option>{faculty.map((name: string) => <option value={name} key={name}>{name}</option>)}</select></label><label>Finalization<select value={filters.state} onChange={e => setFilters({ ...filters, state: e.target.value })}><option value="all">All states</option><option value="finalized">Finalized</option><option value="pending">Pending finalization</option><option value="not_started">Not checked in</option></select></label><label>Section attendance<select value={filters.risk} onChange={e => setFilters({ ...filters, risk: e.target.value })}><option value="all">All available states</option><option value="below_75">Below 75%</option><option value="at_or_above_75">75% and above</option></select></label><button className="btn btn-out" onClick={clear} type="button">Clear filters</button></section>
    <section className="hod-attendance-register" aria-label="Section attendance register"><header><div><p>Section monitoring</p><h2>{visible.length} visible section{visible.length === 1 ? '' : 's'}</h2></div><span>Faculty is derived from active TeachingAllocation records.</span></header><div className="hod-attendance-list">{visible.map((row: any) => <article className="hod-attendance-card" key={row.section_id}><button className="hod-attendance-main" onClick={() => setSelected(row)} type="button"><div className="hod-attendance-ident"><b>{row.course_code}</b><h3>{row.course_title || `Section ${row.section}`}</h3><span>Section {row.section}{row.term ? ` · ${row.term}` : ''}</span></div><Metric label="Faculty" value={row.faculty} /><Metric label="Sessions" value={row.sessions_total} /><Metric label="Finalized" value={row.attendance_finalized} /><Metric label="Pending" value={row.attendance_pending} /><Metric label="Attendance" value={row.attendance_pct == null ? '—' : `${row.attendance_pct}%`} /><Metric label="Below 75%" value={row.students_below_75} /><Status row={row} /></button><div className="hod-attendance-actions"><button onClick={() => setSelected(row)} type="button">View details</button><button onClick={() => go('hod_students')} type="button">Department students</button>{row.attendance_pct !== null && row.attendance_pct < 75 && <button onClick={() => go('hod_risk')} type="button">At-risk students</button>}</div></article>)}{!visible.length && <Empty icon="○" text="No department attendance records match the selected filters." />}</div></section>
    <section className="hod-attendance-risk-register" aria-label="Students below attendance threshold"><header><div><p>Students below threshold</p><h2>{belowThreshold.length} student{belowThreshold.length === 1 ? '' : 's'} below 75%</h2></div><button type="button" onClick={() => go('hod_risk')}>View At-Risk Students →</button></header>{belowThreshold.length ? <div className="hod-attendance-risk-table"><div className="hod-attendance-risk-row labels"><span>Student</span><span>Program / section</span><span>Attendance</span><span>Attended</span><span>Finalized sessions</span><span>Risk</span></div>{belowThreshold.map((row: any) => <div className="hod-attendance-risk-row" key={row.id}><span><b>{row.roll_no}</b><small>{row.name}</small></span><span>{row.program}<small>Section {value(row.section)}</small></span><span>{row.attendance_pct}%</span><span>{row.sessions_attended}</span><span>{row.sessions_considered}</span><span><em>Attendance risk</em></span></div>)}</div> : <p className="hod-attendance-empty">No students with finalized attendance below 75% are currently available.</p>}</section>
    <section className="hod-session-register" aria-label="Session monitoring"><header><div><p>Session monitoring</p><h2>{sessionRows.length} visible session{sessionRows.length === 1 ? '' : 's'}</h2></div><span>Session rows expose finalization state, not individual attendance marks.</span></header>{sessionRows.length ? <div className="hod-session-table"><div className="hod-session-row labels"><span>Date</span><span>Course / section</span><span>Faculty</span><span>State</span><span>Attendance records</span></div>{sessionRows.map((row: any) => <div className="hod-session-row" key={row.id}><span>{value(row.session_date)}</span><span><b>{row.course_code}</b><small>Section {row.section}</small></span><span>{row.faculty}</span><span><em className={row.finalized ? 'finalized' : row.checked_in ? 'pending' : 'scheduled'}>{row.finalized ? 'Finalized' : row.checked_in ? 'Pending finalization' : 'Scheduled'}</em></span><span>{row.attendance_record_count}{row.finalized ? ` / ${row.active_roster_count}` : ''}</span></div>)}</div> : <p className="hod-attendance-empty">No class sessions match the selected filters.</p>}</section>
    {selected && <SectionDetail row={selected} onClose={() => setSelected(null)} go={go} />}
  </main>
}

function Stat({ value, label, helper, tone = '' }: any) { return <article className={tone}><b>{value}</b><span>{label}</span><small>{helper}</small></article> }
function Health({ value, label, tone }: any) { return <article className={tone}><b>{value}</b><span>{label}</span></article> }
function Metric({ label, value: metricValue }: any) { return <div className="hod-attendance-metric"><span>{label}</span><b>{value(metricValue)}</b></div> }
function Status({ row }: any) { return <span className={`hod-attendance-status ${row.attendance_pending ? 'pending' : row.attendance_finalized ? 'finalized' : 'scheduled'}`}>{row.attendance_pending ? 'Pending' : row.attendance_finalized ? 'Finalized' : 'No finalized session'}</span> }
function SectionDetail({ row, onClose, go }: any) { return <Modal className="modal-wide" title={`${row.course_code} · Section ${row.section}`} onClose={onClose} footer={<><button className="btn btn-out" onClick={onClose} type="button">Close</button><button className="btn btn-out" onClick={() => go('hod_students')} type="button">Department Students</button>{row.attendance_pct !== null && row.attendance_pct < 75 && <button className="btn btn-crimson" onClick={() => go('hod_risk')} type="button">At-Risk Students</button>}</>}><section className="hod-attendance-detail"><div className="hod-attendance-detail-info"><span>Faculty ownership</span><b>{row.faculty}</b><span>Scheduled sessions</span><b>{row.sessions_scheduled}</b><span>Conducted sessions</span><b>{row.sessions_conducted}</b><span>Pending finalization</span><b>{row.attendance_pending}</b><span>Finalized sessions</span><b>{row.attendance_finalized}</b><span>Finalized attendance records</span><b>{row.finalized_record_count}</b><span>Attendance percentage</span><b>{row.attendance_pct == null ? 'No finalized attendance records' : `${row.attendance_pct}%`}</b></div><p className="hod-attendance-detail-note">Attendance entries cannot be edited here. Corrections follow the existing workflow from the review workspace.</p></section></Modal> }
