import { useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import { Empty, Modal, Spinner } from '../modules/kit'

const label = (value:string) => String(value || '—').replace(/_/g, ' ').replace(/\b\w/g, letter => letter.toUpperCase())
const date = (value:string) => { if (!value) return '—'; const d=new Date(value); return Number.isNaN(d.valueOf()) ? '—' : d.toLocaleString([], {dateStyle:'medium',timeStyle:'short'}) }
const active = (status:string) => status === 'submitted' || status === 'under_review'

export default function HodCurriculumRequests() {
  const [data,setData]=useState<any>(null), [error,setError]=useState(''), [formOpen,setFormOpen]=useState(false), [selected,setSelected]=useState<any>(null), [query,setQuery]=useState(''), [status,setStatus]=useState('all'), [type,setType]=useState('all'), [program,setProgram]=useState('all')
  const load=async()=>{setError('');try{setData(await api.hodCurriculumRequests())}catch(e:any){setError(e.message||'Curriculum requests could not be loaded.');setData(null)}}
  useEffect(()=>{load()},[])
  const requests=data?.requests||[], options=data?.options||{}, types=options.request_types||[]
  const rows=useMemo(()=>{const needle=query.trim().toLowerCase();return requests.filter((row:any)=>(!needle||`${row.request_type} ${row.proposed_change} ${row.program?.code||''} ${row.program?.name||''} ${row.course?.code||''} ${row.course?.title||''}`.toLowerCase().includes(needle))&&(status==='all'||row.status===status)&&(type==='all'||row.request_type===type)&&(program==='all'||row.program?.id===program))},[requests,query,status,type,program])
  if(!data&&error)return <main className="hod-curriculum-page"><Header department={null} onNew={()=>setFormOpen(true)} onRefresh={load}/><Empty icon="!" text={error}/></main>
  if(!data)return <Spinner/>
  const count=(check:(row:any)=>boolean)=>requests.filter(check).length
  return <main className="hod-curriculum-page fade-in"><Header department={data.department} onNew={()=>setFormOpen(true)} onRefresh={load}/>{error&&<p className="hod-curriculum-message" role="alert">{error}</p>}
    <section className="hod-curriculum-kpis"><Stat value={requests.length} label="Total requests"/><Stat value={count((r:any)=>active(r.status))} label="Awaiting Dean review" tone="review"/><Stat value={count((r:any)=>r.status==='approved')} label="Approved" tone="approved"/><Stat value={count((r:any)=>r.status==='rejected')} label="Rejected" tone="rejected"/></section>
    <section className="hod-curriculum-toolbar"><label>Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Request, program, or course"/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{[...new Set(requests.map((r:any)=>r.status).filter(Boolean))].map((x:any)=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>Request type<select value={type} onChange={e=>setType(e.target.value)}><option value="all">All request types</option>{types.map((x:string)=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>Program<select value={program} onChange={e=>setProgram(e.target.value)}><option value="all">All programs</option>{(options.programs||[]).map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label></section>
    <section className="hod-curriculum-register"><header><div><p>Authenticated HOD requests only</p><h2>Request register</h2></div><span>{rows.length} of {requests.length} requests</span></header><div className="hod-curriculum-table-wrap"><table><thead><tr><th>Request</th><th>Program / course</th><th>Effective semester</th><th>Current reviewer</th><th>Status</th><th>Submitted</th><th>Action</th></tr></thead><tbody>{rows.map((row:any)=><tr key={row.id}><td><b>{label(row.request_type)}</b><small>{row.proposed_change}</small></td><td><b>{row.program?.code||'—'}</b><small>{row.course?`${row.course.code} · ${row.course.title}`:row.program?.name||'Program not recorded'}</small></td><td>{row.effective_semester??'—'}</td><td>{row.current_reviewer||'—'}</td><td><Status value={row.status}/></td><td><span>{date(row.submitted_at)}</span></td><td><button className="hod-curriculum-view" type="button" onClick={()=>setSelected(row)}>View details</button></td></tr>)}{!rows.length&&<tr><td colSpan={7}><Empty icon="⌕" text={requests.length?'No requests match the selected filters.':'No curriculum requests have been submitted by this HOD.'}/></td></tr>}</tbody></table></div></section>
    <section className="hod-curriculum-boundary"><div><p>Workflow boundary</p><h2>Request and approval, not direct curriculum editing</h2></div><ol><li>HOD submits a department-scoped proposal.</li><li>Dean Academics is resolved by the backend for the HOD campus.</li><li>Dean approves or rejects; final requests remain read-only.</li></ol></section>
    {formOpen&&<RequestForm options={options} onClose={()=>setFormOpen(false)} onSaved={async()=>{setFormOpen(false);await load()}}/>}{selected&&<Detail request={selected} onClose={()=>setSelected(null)}/>}</main>
}
function Header({department,onNew,onRefresh}:any){return <header className="hod-curriculum-head"><div><p>{department?`${department.name} · ${department.campus||'Campus not recorded'}`:'Department academic proposals'}</p><h1>Curriculum Requests</h1><span>Submit a department curriculum request to the backend-resolved Dean Academics reviewer.</span></div><div><button className="btn btn-out" type="button" onClick={onRefresh}>Refresh</button><button className="btn btn-crimson" type="button" onClick={onNew}>New Curriculum Request</button></div></header>}
function Stat({value,label,tone=''}:any){return <article className={tone}><b>{value}</b><span>{label}</span></article>}
function Status({value}:any){return <span className={`hod-curriculum-status ${String(value||'').replace(/_/g,'-')}`}>{label(value)}</span>}
function RequestForm({options,onClose,onSaved}:any){const [form,setForm]=useState<any>({request_type:'',program_id:'',course_id:'',proposed_change:'',rationale:'',effective_semester:''}),[saving,setSaving]=useState(false),[error,setError]=useState('');const courses=(options.courses||[]).filter((course:any)=>course.program_id===form.program_id);const courseRequired=form.request_type&&form.request_type!=='program_curriculum_change';const submit=async(e:any)=>{e.preventDefault();if(courseRequired&&!form.course_id){setError('Choose the department course for this request type.');return}setSaving(true);setError('');try{await api.createHodCurriculumRequest({...form,course_id:form.course_id||null,effective_semester:form.effective_semester?Number(form.effective_semester):null});await onSaved()}catch(reason:any){setError(reason.message||'Curriculum request could not be submitted.')}finally{setSaving(false)}};return <Modal className="modal-wide hod-curriculum-modal" title="New Curriculum Request" onClose={onClose} footer={<><button className="btn btn-out" onClick={onClose} type="button" disabled={saving}>Cancel</button><button className="btn btn-crimson" form="hod-curriculum-form" type="submit" disabled={saving}>{saving?'Submitting…':'Submit to Dean Academics'}</button></>}><form id="hod-curriculum-form" className="hod-curriculum-form" onSubmit={submit}><p>Submitting a request does not change Program or Course records directly.</p><label>Request type<select required value={form.request_type} onChange={e=>setForm({...form,request_type:e.target.value,course_id:''})}><option value="">Select request type</option>{(options.request_types||[]).map((x:string)=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>Program<select required value={form.program_id} onChange={e=>setForm({...form,program_id:e.target.value,course_id:''})}><option value="">Select department program</option>{(options.programs||[]).map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label>{form.request_type!=='program_curriculum_change'&&<label>Course <small>Required for the selected request type.</small><select required={!!courseRequired} disabled={!form.program_id} value={form.course_id} onChange={e=>setForm({...form,course_id:e.target.value})}><option value="">Select department course</option>{courses.map((x:any)=><option key={x.id} value={x.id}>{x.code} · {x.title}</option>)}</select></label>}<label>Effective semester <small>Optional</small><input type="number" min="1" value={form.effective_semester} onChange={e=>setForm({...form,effective_semester:e.target.value})}/></label><label>Proposed change<textarea required value={form.proposed_change} onChange={e=>setForm({...form,proposed_change:e.target.value})}/></label><label>Rationale<textarea required value={form.rationale} onChange={e=>setForm({...form,rationale:e.target.value})}/></label>{error&&<p className="hod-curriculum-message" role="alert">{error}</p>}</form></Modal>}
function Detail({request,onClose}:any){return <Modal className="modal-wide hod-curriculum-modal" title="Curriculum Request" onClose={onClose} footer={<button className="btn btn-out" onClick={onClose} type="button">Close</button>}><div className="hod-curriculum-detail"><section><Field label="Request type" value={label(request.request_type)}/><Field label="Status" value={label(request.status)}/><Field label="Program" value={request.program?`${request.program.code} · ${request.program.name}`:'—'}/><Field label="Course" value={request.course?`${request.course.code} · ${request.course.title}`:'Not course-specific'}/><Field label="Effective semester" value={request.effective_semester??'—'}/><Field label="Current reviewer" value={request.current_reviewer||'—'}/><Field label="Submitted" value={date(request.submitted_at)}/></section><Text label="Proposed change" value={request.proposed_change}/><Text label="Rationale" value={request.rationale}/><section className="hod-curriculum-history"><h3>Workflow history</h3>{request.history?.length?request.history.map((item:any,index:number)=><div key={index}><b>{item.stage_label} · {item.decision}</b><span>{item.actor} · {date(item.at)}{item.reason?` — ${item.reason}`:''}</span></div>):<p>No Dean decision has been recorded.</p>}</section><p className="hod-curriculum-readonly">This request is read-only. The current backend does not support HOD edit, return, resubmit, or reviewer selection.</p></div></Modal>}
function Field({label,value}:any){return <div><span>{label}</span><b>{value}</b></div>};function Text({label,value}:any){return <section className="hod-curriculum-text"><h3>{label}</h3><p>{value||'—'}</p></section>}
