import { useEffect, useState } from 'react';
import { api } from '../api';
import { Empty, Spinner } from '../modules/kit';

const gapCopy: Record<string, [string, string]> = {
  course_without_section: ['Course without section', 'Course delivery has not been represented by a stored section.'],
  section_without_faculty: ['Section without faculty', 'No current teaching allocation is recorded.'],
  section_without_timetable: ['Section without timetable', 'No active timetable entry is recorded.'],
};

export default function HodDepartmentPlanning({ go }: { go: (view: string) => void }) {
  const [semester, setSemester] = useState<number | ''>('');
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState('');
  const load = async (nextSemester = semester) => { setError(''); try { setData(await api.hodDepartmentPlanning(nextSemester)); } catch (reason: any) { setError(reason.message || 'Department planning could not be loaded.'); } };
  useEffect(() => { load(''); }, []);
  if (error && !data) return <Empty icon="!" text={error} />;
  if (!data) return <Spinner />;
  const summary = data.summary || {}, attention = data.attention || [], courses = data.courses || [], terms = data.period?.stored_terms || [];
  const allocation = measure(summary.sections_with_faculty, summary.sections);
  const timetable = measure(summary.sections_with_timetable, summary.sections);
  const filterAvailable = (data.period?.available_semesters || []).length > 0;
  const changeSemester = (value: string) => { const next = value ? Number(value) : ''; setSemester(next); load(next); };
  const kpis = [['Active Courses', summary.active_courses, 'Courses marked active', 'hod_courses'], ['Active Sections', summary.sections, 'Stored section records', 'hod_sections'], ['Active Faculty', summary.active_faculty, 'Active department staff', 'hod_faculty'], ['Allocation Readiness', allocation.percent, allocation.ratio, 'hod_allocations'], ['Timetable Readiness', timetable.percent, timetable.ratio, 'hod_sections'], ['Planning Gaps', summary.attention_count, 'Recorded delivery gaps', 'hod_planning']];

  return <main className="hod-plan-command fade-in">
    <header className="hod-plan-header"><div><p>DEPARTMENT READINESS COORDINATION</p><h1>Department Planning</h1><span>{data.department?.name || 'Department'} · {data.period?.label || 'Stored planning data'}{terms.length ? ` · ${terms.join(', ')}` : ''}</span></div><div className="hod-plan-tools">{filterAvailable && <label>Semester<select value={semester} onChange={event => changeSemester(event.target.value)}><option value="">All stored semesters</option>{data.period.available_semesters.map((item: number) => <option value={item} key={item}>Semester {item}</option>)}</select></label>}<button className="btn btn-out" onClick={() => load()} type="button">Refresh</button></div></header>
    {error && <p className="hod-allocation-message error">{error}</p>}
    <section className="hod-plan-kpis">{kpis.map(([label, value, support, view]: any, index) => <button className={`hod-plan-kpi tone-${index}`} key={label} onClick={() => go(view)} type="button"><span>{label}</span><b>{value ?? '—'}</b><small>{support}</small></button>)}</section>
    <section className="hod-plan-structure"><PlanCard title="Programs & Courses" value={summary.active_courses} detail={`${summary.courses ?? 0} stored courses in this planning scope`} action="View Programs & Courses" onClick={() => go('hod_courses')} /><PlanCard title="Teaching Allocations" value={allocation.ratio} detail={`${allocation.percent} sections covered by a current allocation`} action="View Teaching Allocations" onClick={() => go('hod_allocations')} /><PlanCard title="Sections & Timetable" value={timetable.ratio} detail={`${timetable.percent} sections with active timetable coverage`} action="View Sections & Timetable" onClick={() => go('hod_sections')} /><PlanCard title="Student Strength" value={summary.active_students} detail="Active students in the selected planning scope" action="View Department Students" onClick={() => go('hod_students')} /></section>
    <section className="hod-plan-two"><section className="hod-plan-card"><header><div><p>Faculty coverage</p><h2>Faculty & Workload</h2></div><button onClick={() => go('hod_faculty')} type="button">View Faculty & Workload →</button></header><div className="hod-plan-faculty"><Metric label="Active Faculty" value={summary.active_faculty} /><Metric label="Allocated Faculty" value={summary.allocated_faculty} /><Metric label="Unallocated Faculty" value={summary.unallocated_faculty} /><Metric label="Uncovered Sections" value={summary.sections_without_faculty} /></div></section><section className="hod-plan-card"><header><div><p>Delivery coverage</p><h2>Sections & Timetable</h2></div><button onClick={() => go('hod_sections')} type="button">Open Sections & Timetable →</button></header><div className="hod-plan-coverage"><Coverage label="Sections with timetable" item={timetable} /><Coverage label="Sections without timetable" item={{ ...timetable, numerator: summary.sections_without_timetable, denominator: summary.sections, percent: summary.sections ? `${Math.round(summary.sections_without_timetable * 100 / summary.sections)}%` : '—' }} danger /></div></section></section>
    <section className="hod-plan-card hod-plan-attention"><header><div><p>Real planning gaps</p><h2>Needs Attention</h2></div></header>{attention.length ? <div>{attention.map((item: any, index: number) => { const [type, explanation] = gapCopy[item.kind] || [label(item.kind), 'A stored planning record needs attention.']; return <button key={`${item.kind}-${index}`} type="button" onClick={() => go(item.view)}><span className="hod-plan-gap-badge">Attention</span><div><b>{type}</b><strong>{item.label}</strong><small>{explanation}</small></div><em>Open →</em></button>; })}</div> : <p className="hod-plan-empty">No current course, allocation, or timetable gaps were returned for this department.</p>}</section>
    <section className="hod-plan-card hod-plan-table"><header><div><p>Read-only delivery monitor</p><h2>Course / Section Delivery Coverage</h2></div><span>Authoritative shared academic records</span></header><div className="hod-plan-table-wrap"><table><thead><tr><th>Course</th><th>Semester</th><th>Current sections</th><th>Faculty coverage</th><th>Timetable coverage</th><th>Student strength</th><th>Planning status</th></tr></thead><tbody>{courses.map((course: any) => { const sections = course.sections || []; const assigned = sections.filter((row: any) => row.has_current_faculty).length; const timed = sections.filter((row: any) => row.active_timetable_entries > 0).length; const ready = sections.length > 0 && assigned === sections.length && timed === sections.length; return <tr key={course.id}><td><b>{course.code}</b><small>{course.title}</small></td><td>{course.semester ?? '—'}</td><td>{sections.length}</td><td>{measure(assigned, sections.length).ratio}</td><td>{measure(timed, sections.length).ratio}</td><td>{sections.reduce((total: number, row: any) => total + Number(row.enrolled_students || 0), 0)}</td><td><span className={`hod-plan-status ${ready ? 'ready' : 'attention'}`}>{ready ? 'Ready' : 'Attention required'}</span></td></tr>; })}{!courses.length && <tr><td colSpan={7}>No stored courses match this planning period.</td></tr>}</tbody></table></div></section>
  </main>;
}

function PlanCard({ title, value, detail, action, onClick }: any) { return <button className="hod-plan-structure-card" onClick={onClick} type="button"><span>{title}</span><b>{value ?? '—'}</b><small>{detail}</small><em>{action} →</em></button>; }
function Metric({ label: text, value }: any) { return <div><span>{text}</span><b>{value ?? '—'}</b></div>; }
function Coverage({ label: text, item, danger = false }: any) { return <article className={danger ? 'danger' : ''}><div><span>{text}</span><b>{item.percent}</b></div><small>{item.ratio}</small><i><em style={{ width: `${item.percent === '—' ? 0 : Number(String(item.percent).replace('%', ''))}%` }} /></i></article>; }
function measure(numerator: any, denominator: any) { const total = Number(denominator || 0), count = Number(numerator || 0); return { numerator: count, denominator: total, ratio: total ? `${count} / ${total}` : '—', percent: total ? `${Math.round(count * 100 / total)}%` : '—' }; }
function label(value: string) { return String(value || 'Planning gap').replace(/_/g, ' ').replace(/\b\w/g, item => item.toUpperCase()); }
