import { useEffect, useMemo, useState } from 'react'
import { api } from '../api'
import { Empty, Modal, Spinner } from '../modules/kit'

type Paper = { id:string; assessment:string; assessment_type:string; course_code:string; course_title:string; section:string; term:string; scheduled_at:string; scheduled_end:string; schedule_status:string; venue:string; mode:string; schedule_ready:boolean; faculty:string; faculty_assigned:boolean; marks_state:string; marks_submitted:boolean; published:boolean; awaiting_hod:boolean }
const title = (value:string) => String(value || '—').replace(/_/g, ' ').replace(/\b\w/g, x => x.toUpperCase())
const dateTime = (value:string) => { if (!value) return 'Not scheduled'; const date = new Date(value); return Number.isNaN(date.valueOf()) ? 'Not scheduled' : date.toLocaleString([], { dateStyle:'medium', timeStyle:'short' }) }
const percent = (a:number,b:number) => b ? Math.round((a / b) * 100) : null

export default function HodExaminationCoordination({ go }: { go:(view:string)=>void }) {
  const [data, setData] = useState<any>(null), [error, setError] = useState(''), [query, setQuery] = useState('')
  const [term, setTerm] = useState('all'), [schedule, setSchedule] = useState('all'), [marks, setMarks] = useState('all'), [selected, setSelected] = useState<Paper | null>(null)
  const load = async () => { setError(''); try { setData(await api.hodExaminations()) } catch (e:any) { setError(e.message || 'Examination coordination could not be loaded.'); setData(null) } }
  useEffect(() => { load() }, [])
  const papers:Paper[] = useMemo(() => (data?.exams || []).filter((row:Paper, index:number, all:Paper[]) => all.findIndex(candidate => candidate.id === row.id) === index), [data])
  const terms = useMemo(() => [...new Set(papers.map(row => row.term).filter(Boolean))].sort(), [papers])
  const filtered = useMemo(() => { const needle=query.trim().toLowerCase(); return papers.filter(row => (!needle || `${row.assessment} ${row.course_code} ${row.course_title} ${row.section}`.toLowerCase().includes(needle)) && (term === 'all' || row.term === term) && (schedule === 'all' || (schedule === 'scheduled' ? row.schedule_ready : !row.schedule_ready)) && (marks === 'all' || row.marks_state === marks)) }, [papers, query, term, schedule, marks])
  if (!data && error) return <main className="hod-exam-page"><Header department={null} onRefresh={load}/><Empty icon="!" text={error}/></main>
  if (!data) return <Spinner />
  const summary=data.summary || {}, readiness=data.readiness || {}, attention=(data.attention || []).slice(0, 8)
  return <main className="hod-exam-page fade-in">
    <Header department={data.department} onRefresh={load}/>
    {error && <p className="hod-exam-message" role="alert">{error}</p>}
    <section className="hod-exam-kpis"><Kpi value={summary.assessments} label="Department assessments"/><Kpi value={summary.scheduled_papers} label="Scheduled papers"/><Kpi value={summary.unscheduled_papers} label="Unscheduled papers" tone="warn"/><Kpi value={summary.marks_submitted} label="Marks submitted"/><Kpi value={summary.marks_pending} label="Marks pending" tone="warn"/><Kpi value={summary.hod_reviews_pending} label="HOD reviews pending" tone="review"/></section>
    <section className="hod-exam-readiness"><Readiness label="Timetable coverage" helper="Active scheduled timetable entries" value={readiness.timetable}/><Readiness label="Faculty coverage" helper="Active allocation on the assessment date" value={readiness.faculty}/><Readiness label="Marks submission" helper="Submitted, under review, or published marks" value={readiness.marks_submission}/><article className="hod-exam-review-card"><span>HOD review queue</span><b>{summary.hod_reviews_pending || 0}</b><p>Only items currently assigned to this HOD.</p><button type="button" onClick={() => go('hod_reviews_marks')}>Open My Reviews →</button></article></section>
    <section className="hod-exam-toolbar"><label>Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Assessment, course, or section"/></label><label>Term<select value={term} onChange={e=>setTerm(e.target.value)}><option value="all">All terms</option>{terms.map(value=><option key={value} value={value}>{value}</option>)}</select></label><label>Timetable<select value={schedule} onChange={e=>setSchedule(e.target.value)}><option value="all">All papers</option><option value="scheduled">Scheduled</option><option value="unscheduled">Unscheduled</option></select></label><label>Marks status<select value={marks} onChange={e=>setMarks(e.target.value)}><option value="all">All statuses</option>{[...new Set(papers.map(row=>row.marks_state).filter(Boolean))].sort().map(value=><option key={value} value={value}>{title(value)}</option>)}</select></label></section>
    <section className="hod-exam-register"><header><div><p>Department paper coordination</p><h2>Assessment register</h2></div><span>{filtered.length} of {papers.length} papers</span></header><div className="hod-exam-table-wrap"><table><thead><tr><th>Assessment</th><th>Course / section</th><th>Timetable</th><th>Faculty</th><th>Marks submission</th><th>HOD review</th><th>Action</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td><b>{row.assessment || 'Assessment'}</b><small>{title(row.assessment_type)}</small></td><td><b>{row.course_code || '—'}</b><small>{row.course_title || 'Course not recorded'} · Section {row.section || '—'}</small></td><td><Status value={row.schedule_ready ? title(row.schedule_status) : 'Not scheduled'} type={row.schedule_ready ? 'ok' : 'warn'}/><small>{row.schedule_ready ? `${dateTime(row.scheduled_at)} · ${row.venue || 'Venue not recorded'}` : 'No active assessment timetable entry'}</small></td><td><b>{row.faculty || 'Not allocated'}</b><small>{row.faculty_assigned ? 'Current teaching allocation' : 'No active allocation'}</small></td><td><Status value={title(row.marks_state || 'draft')} type={row.marks_submitted ? 'ok' : 'warn'}/><small>{row.published ? 'Marks published' : row.marks_submitted ? 'Workflow in progress' : 'Awaiting submission'}</small></td><td><Status value={row.awaiting_hod ? 'Awaiting HOD' : 'Not awaiting HOD'} type={row.awaiting_hod ? 'review' : 'neutral'}/></td><td><div className="hod-exam-actions"><button type="button" onClick={()=>setSelected(row)}>View</button>{row.awaiting_hod && <button type="button" className="review" onClick={()=>go('hod_reviews_marks')}>Review</button>}</div></td></tr>)}{!filtered.length && <tr><td colSpan={7}><Empty icon="⌕" text={papers.length ? 'No papers match these filters.' : 'No department assessments are available.'}/></td></tr>}</tbody></table></div></section>
    <section className="hod-exam-bottom"><article className="hod-exam-attention"><header><div><p>Operational gaps</p><h2>Needs attention</h2></div><span>{attention.length}</span></header>{attention.length ? attention.map((item:any,index:number)=><div key={`${item.type}-${item.course_code}-${index}`}><i className={item.type}/><section><b>{title(item.type)} · {item.course_code || 'Course'} {item.section ? `· Section ${item.section}` : ''}</b><span>{item.assessment || 'Assessment'} — {item.message}</span></section><button type="button" onClick={()=>go(item.target)}>Open →</button></div>) : <Empty icon="✓" text="No schedule, allocation, marks-submission, or current HOD-review gaps were found."/>}</article><article className="hod-exam-boundary"><p>Coordination boundary</p><h2>Read-only department oversight</h2><ul><li>Timetable records remain owned by the examination authority.</li><li>Professors enter and submit marks for assigned sections.</li><li>HOD decisions remain in My Reviews when HOD is the resolved reviewer.</li><li>Result publication is not available from this workspace.</li></ul></article></section>
    {selected && <Detail row={selected} onClose={()=>setSelected(null)} onReview={()=>go('hod_reviews_marks')}/>} 
  </main>
}
function Header({department,onRefresh}:any){return <header className="hod-exam-head"><div><p>{department ? `${department.name} · ${department.campus || 'Campus not recorded'}` : 'Department examination scope'}</p><h1>Examination Coordination</h1><span>Department readiness monitoring. Marks decisions and result publication remain in their authoritative workflows.</span></div><button className="btn btn-out" type="button" onClick={onRefresh}>Refresh</button></header>}
function Kpi({value,label,tone=''}:any){return <article className={tone}><b>{value ?? 0}</b><span>{label}</span></article>}
function Readiness({label,helper,value}:any){const numerator=value?.numerator || 0, denominator=value?.denominator || 0, pct=percent(numerator,denominator);return <article><header><span>{label}</span><b>{pct == null ? '—' : `${pct}%`}</b></header><p>{numerator} / {denominator} · {helper}</p><i><em style={{width:`${pct || 0}%`}}/></i></article>}
function Status({value,type}:any){return <span className={`hod-exam-status ${type}`}>{value}</span>}
function Detail({row,onClose,onReview}:any){return <Modal className="modal-wide hod-exam-modal" title={row.assessment || 'Assessment details'} onClose={onClose} footer={<><button className="btn btn-out" type="button" onClick={onClose}>Close</button>{row.awaiting_hod && <button className="btn btn-crimson" type="button" onClick={onReview}>Review in My Reviews</button>}</>}><div className="hod-exam-detail"><section>{[['Course',`${row.course_code || '—'} · ${row.course_title || '—'}`],['Section',row.section || '—'],['Term',row.term || '—'],['Assessment type',title(row.assessment_type)],['Schedule',row.schedule_ready ? dateTime(row.scheduled_at) : 'Not scheduled'],['Venue / mode',row.schedule_ready ? `${row.venue || 'Venue not recorded'} · ${row.mode || 'Mode not recorded'}` : '—'],['Faculty',row.faculty || 'No active allocation'],['Marks workflow',title(row.marks_state)],['HOD review',row.awaiting_hod ? 'Awaiting HOD review' : 'Not awaiting HOD']].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</section><p>This view contains coordination metadata only; it does not expose student-level marks or provide timetable, marks, or result-publication controls.</p></div></Modal>}
