import { useEffect, useState } from 'react'
import { api } from '../api'
import { Spinner, Empty } from './ui'

export default function AuditView() {
  const [rows, setRows] = useState<any[]>([]), [loading, setLoading] = useState(true), [verify, setVerify] = useState<any>(null), [verifying, setVerifying] = useState(false), [error, setError] = useState(''), [unavailable, setUnavailable] = useState('')
  function load() { setError(''); setLoading(true); api.audit().then(response => { setRows(response.entries); setUnavailable(response.data_status === 'unavailable' ? response.reason || 'Campus-scoped audit data is unavailable.' : '') }).catch(() => setError('Unable to load audit entries.')).finally(() => setLoading(false)) }
  useEffect(load, [])
  async function runVerify() { setVerifying(true); setError(''); try { const result = await api.verifyAudit(); setVerify(result); if (result.data_status === 'unavailable') setUnavailable(result.reason || 'Campus-scoped audit data is unavailable.') } catch { setError('Unable to verify chain integrity.') } finally { setVerifying(false) } }
  const tone = (outcome: string) => outcome === 'ALLOW' ? 'var(--teal)' : outcome === 'DENY' ? 'var(--rose)' : outcome === 'ESCALATE' ? 'var(--amber)' : '#8f1736'
  if (unavailable) return <div className="fade-in principal-operations audit-page"><div className="audit-head"><div><h1>Audit log</h1><p>Every authority decision is recorded in the hash-chained ledger for review and verification.</p></div></div><div className="audit-error">{unavailable}</div></div>
  return <div className="fade-in principal-operations audit-page"><div className="audit-head"><div><h1>Audit log</h1><p>Every authority decision is recorded in the hash-chained ledger for review and verification.</p></div><button className="btn btn-crimson" onClick={runVerify} disabled={verifying}>{verifying ? 'Verifying…' : 'Verify chain integrity'}</button></div>{verify && <div className={`audit-verify ${verify.intact ? 'valid' : 'invalid'}`}><i>{verify.intact ? '✓' : '!'}</i><div><b>{verify.intact ? 'Chain verified' : 'Chain broken'}</b><p>{verify.intact ? `All ${verify.count} entries verified — chain integrity confirmed.` : `${verify.count} entries verified — break at entry ${verify.broken_at}.`}</p></div></div>}{error && <div className="audit-error">{error}<button className="btn btn-out" onClick={error.includes('verify') ? runVerify : load}>Retry</button></div>}{loading ? <Spinner /> : <section className="card audit-card"><div className="audit-card-head"><div><span>Immutable ledger</span><h3>Audit entries</h3></div><b>{rows.length} entries</b></div><div className="tbl-scroll">{rows.length === 0 ? <Empty icon="◇" text="No audit entries yet. Decisions will be recorded here as workflows run." /> : <table className="tbl audit-table"><thead><tr><th>#</th><th>When</th><th>Actor</th><th>Action</th><th>Campus</th><th>Outcome</th><th>Reason</th><th>Hash</th></tr></thead><tbody>{rows.map((entry, index) => <tr key={entry.id}><td className="mono">{rows.length - index}</td><td className="mono">{new Date(entry.at).toLocaleString()}</td><td>{entry.actor}</td><td><span className="mono">{entry.action}</span></td><td className="mono">{entry.campus_scope_id || '—'}</td><td><span className="audit-outcome" style={{ color: tone(entry.outcome) }}>{entry.outcome}</span></td><td className="audit-reason">{entry.reason}</td><td className="mono audit-hash" title={entry.hash}>{entry.hash?.slice(0, 10)}…</td></tr>)}</tbody></table>}</div></section>}</div>
}
