import { useEffect, useState } from 'react'
import { api } from '../api'
import { Empty, Spinner, StatePill, money } from './ui'

export function PrincipalApprovals({ user, onChange }: { user: any; onChange: () => void }) {
  const [workflows, setWorkflows] = useState<any[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [selected, setSelected] = useState<any>(null)
  const [stateFilter, setStateFilter] = useState(''), [processFilter, setProcessFilter] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const response = await api.workflows('inbox'); setWorkflows(response.workflows || []) } catch (e: any) { setError(e.message || 'Unable to load approvals.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const filtered = workflows.filter(item => (!stateFilter || item.state === stateFilter) && (!processFilter || item.process_key === processFilter))
  const counts = { all: workflows.length, progress: workflows.filter(item => ['submitted', 'under_review', 'reviewed'].includes(item.state)).length, escalated: workflows.filter(item => item.state === 'escalated').length, completed: workflows.filter(item => ['approved', 'executed', 'rejected'].includes(item.state)).length }
  const processOptions = [...new Map(workflows.map(item => [item.process_key, item.label])).entries()]
  const actionLabel = (item: any) => item.available_actions?.includes('approve') || item.available_actions?.includes('reject') ? 'Decision required' : item.available_actions?.includes('review') ? 'Review required' : item.available_actions?.includes('escalate') ? 'Escalation review' : 'Action required'
  return <div className="fade-in principal-operations workflow-page approval-action-center"><div className="workflow-head"><div><p className="eyebrow">ACTION CENTER</p><h1>My Approvals</h1><p>Requests waiting for your decision</p></div></div><div className="workflow-summary">{[['Needs My Action', counts.all], ['In Review', counts.progress], ['Escalated', counts.escalated], ['Completed', counts.completed]].map(([label, value]) => <div className="workflow-stat" key={String(label)}><span>{label}</span><b>{value}</b></div>)}</div><div className="workflow-filters"><select className="select" value={processFilter} onChange={event => setProcessFilter(event.target.value)}><option value="">All processes</option>{processOptions.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><select className="select" value={stateFilter} onChange={event => setStateFilter(event.target.value)}><option value="">All states</option>{[...new Set(workflows.map(item => item.state))].map(state => <option key={state}>{state}</option>)}</select></div>{error && <div className="workflow-error">{error}<button className="btn btn-out" onClick={() => void load()}>Retry</button></div>}{loading ? <Spinner /> : <section className="card workflow-list-card"><div className="tbl-scroll">{filtered.length === 0 ? <Empty icon="◇" text="No requests need your action." /> : <table className="tbl workflow-table"><thead><tr><th>Process</th><th>Request</th><th>Initiator</th><th>Amount</th><th>Campus</th><th>Stage</th><th>State</th><th>Required action</th><th /></tr></thead><tbody>{filtered.map(item => <tr key={item.id}><td><b>{item.label}</b></td><td className="workflow-title">{item.title}</td><td>{item.initiator}</td><td>{item.amount == null ? '—' : money(item.amount)}</td><td>{item.campus || 'Institution-wide'}</td><td className="mono">{Number(item.current_stage || 0) + 1}/{item.chain?.length || 0}</td><td><StatePill s={item.state} /></td><td><b className="workflow-required">{actionLabel(item)}</b></td><td><button className="btn btn-crimson" onClick={() => setSelected(item)}>Review</button></td></tr>)}</tbody></table>}</div></section>}{selected && <PrincipalApprovalDetail wf={selected} onClose={() => setSelected(null)} onDone={() => { setSelected(null); void load(); onChange() }} />}</div>
}

function PrincipalApprovalDetail({ wf, onClose, onDone }: any) {
  const [data, setData] = useState<any>(wf), [reason, setReason] = useState(''), [busy, setBusy] = useState(''), [error, setError] = useState('')
  useEffect(() => { api.workflow(wf.id).then(setData).catch((e: any) => setError(e.message || 'Unable to load workflow details.')) }, [wf.id])
  const decide = async (action: string) => { setBusy(action); setError(''); try { await api.decideWorkflow(data.id, action, reason, data.version_no) ; onDone() } catch (e: any) { setError(e.message || 'Unable to update workflow.') } finally { setBusy('') } }
  const terminal = ['approved', 'executed', 'rejected'].includes(data.state), available = Array.isArray(data.available_actions) && data.available_actions.length ? data.available_actions : (terminal ? [] : ['review', 'approve', 'reject', 'return', 'escalate'])
  return <div className="modal-bg" onClick={onClose}><div className="modal principal-workflow-modal" onClick={event => event.stopPropagation()}><div className="modal-h"><div><h3>{data.label}</h3><p>{data.title}</p></div><button className="modal-x" onClick={onClose}>×</button></div><div className="modal-b workflow-modal-body">{error && <div className="workflow-error">{error}</div>}<div className="workflow-meta"><Meta label="State"><StatePill s={data.state} /></Meta><Meta label="Initiator">{data.initiator}</Meta><Meta label="Amount"><span className="mono">{money(data.amount)}</span></Meta><Meta label="Scope"><span className="mono">{data.scope_level}</span></Meta><Meta label="Escalates to">{data.escalation || 'Not configured'}</Meta></div><section className="workflow-section"><h4>Approval chain</h4><div className="workflow-chain">{(data.chain || []).map((name: string, index: number) => <div className={`workflow-stage ${index < data.current_stage ? 'done' : index === data.current_stage && !terminal ? 'current' : ''}`} key={`${name}-${index}`}><span>Stage {index}</span><b>{name}</b></div>)}</div></section><section className="workflow-section"><h4>Decision history</h4>{data.history?.length ? <div className="workflow-history">{data.history.map((item: any, index: number) => <div key={index}><b>{item.decision}</b><span>{item.actor} · {item.stage_label}</span><p>{item.reason}</p></div>)}</div> : <p className="workflow-empty">No decision history is available.</p>}</section>{!terminal && <label className="workflow-field workflow-reason">Reason / remarks<textarea className="inp" value={reason} onChange={event => setReason(event.target.value)} rows={3} placeholder="Optional note recorded in the audit trail" /></label>}</div><div className="modal-f workflow-modal-footer">{available.length && !terminal ? <>{available.includes('review') && <button className="btn btn-out" disabled={!!busy} onClick={() => void decide('review')}>Review</button>}{available.includes('approve') && <button className="btn btn-crimson" disabled={!!busy} onClick={() => void decide('approve')}>Approve</button>}{available.includes('reject') && <button className="btn btn-rose" disabled={!!busy} onClick={() => void decide('reject')}>Reject</button>}{available.includes('return') && <button className="btn btn-out" disabled={!!busy} onClick={() => void decide('return')}>Return</button>}{available.includes('escalate') && <button className="btn btn-out" disabled={!!busy} onClick={() => void decide('escalate')}>Escalate</button>}</> : <span className="workflow-unavailable">This request has reached a terminal state.</span>}</div></div></div>
}

function Meta({ label, children }: any) { return <div><span>{label}</span><b>{children}</b></div> }

export function ApprovalHistory() {
  const [data, setData] = useState<any>(null), [q, setQ] = useState(''), [action, setAction] = useState('')
  const load = () => { setData(null); api.approvalHistory({ q, action }).then(setData).catch(() => setData({ error: true, events: [] })) }
  useEffect(() => { load() }, [])
  if (!data) return <Spinner />
  return <div className="fade-in principal-operations approval-history-page"><div className="page-head"><h1>Approval History</h1><p>Recorded workflow decisions for this institution.</p></div><div className="operations-filter"><input className="inp" value={q} onChange={event => setQ(event.target.value)} placeholder="Search request, module or approver" /><select className="select" value={action} onChange={event => setAction(event.target.value)}><option value="">All actions</option>{['ALLOW', 'DENY', 'ESCALATE', 'RECOMMEND'].map(item => <option key={item}>{item}</option>)}</select><button className="btn btn-crimson" onClick={load}>Filter</button><button className="btn btn-out" onClick={() => { setQ(''); setAction(''); setTimeout(load, 0) }}>Clear</button></div>{data.error ? <p className="principal-empty">Unable to load approval history. Please try again.</p> : <section className="card approval-history-card"><div className="tbl-scroll"><table className="tbl approval-history-table"><thead><tr><th>Request</th><th>Module</th><th>Requested by</th><th>Action</th><th>Approver</th><th>Comments</th><th>Date</th></tr></thead><tbody>{(data.events || []).map((item: any) => <tr key={item.id}><td><b>{item.request}</b></td><td>{item.module}</td><td>{item.requested_by}</td><td><span className="tag">{item.action}</span></td><td>{item.approver}</td><td>{item.reason || '—'}</td><td>{item.at ? new Date(item.at).toLocaleString() : '—'}</td></tr>)}</tbody></table>{!data.events?.length && <p className="principal-empty">No approval events match these filters.</p>}</div></section>}</div>
}

export function Escalations() {
  const [data, setData] = useState<any>(null), [q, setQ] = useState(''), [state, setState] = useState('')
  const load = () => { setData(null); api.escalations({ q, state }).then(setData).catch(() => setData({ error: true, incoming: [], outgoing: [] })) }
  useEffect(() => { load() }, [])
  if (!data) return <Spinner />
  const Table = ({ title, rows }: any) => <section className="card" style={{ marginTop: 16 }}><div className="card-h"><h3>{title}</h3><span className="hint">{rows.length} records</span></div><div className="tbl-scroll"><table className="tbl"><thead><tr><th>Reference</th><th>Module</th><th>Request</th><th>From</th><th>Escalates to</th><th>Status</th><th>Created</th></tr></thead><tbody>{rows.map((item: any) => <tr key={item.id}><td className="mono">{item.reference}</td><td>{item.module}</td><td><b>{item.title}</b></td><td>{item.from}</td><td>{item.to || '—'}</td><td><span className="tag">{item.status}</span></td><td>{new Date(item.created_at).toLocaleDateString()}</td></tr>)}</tbody></table>{!rows.length && <p className="principal-empty">No escalation records match these filters.</p>}</div></section>
  return <div className="fade-in principal-operations"><div className="page-head"><h1>Escalations</h1><p>Incoming and outgoing workflow and campus-risk escalations.</p></div><div className="operations-filter"><input className="inp" value={q} onChange={event => setQ(event.target.value)} placeholder="Search request, module or initiator" /><select className="select" value={state} onChange={event => setState(event.target.value)}><option value="">All statuses</option><option value="escalated">Escalated</option>{['DRAFT', 'SUBMITTED', 'RECEIVED', 'FOLLOW_UP', 'RESOLVED', 'CLOSED'].map(value => <option key={value} value={value}>{value.replace('_', ' ')}</option>)}</select><button className="btn btn-crimson" onClick={load}>Filter</button><button className="btn btn-out" onClick={() => { setQ(''); setState(''); setTimeout(load, 0) }}>Clear</button></div>{data.error ? <p className="principal-empty">Unable to load escalations. Please try again.</p> : <><Table title="Incoming Escalations" rows={data.incoming || []} /><Table title="Outgoing Escalations" rows={data.outgoing || []} /></>}</div>
}

export function PrincipalWorkflows({ user, onChange }: { user: any; onChange: () => void }) {
  const [workflows, setWorkflows] = useState<any[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [selected, setSelected] = useState<any>(null), [showStart, setShowStart] = useState(false)
  const [stateFilter, setStateFilter] = useState(''), [processFilter, setProcessFilter] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const response = await api.workflows('all'); setWorkflows(response.workflows || []) } catch (e: any) { setError(e.message || 'Unable to load workflows.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const filtered = workflows.filter(item => (!stateFilter || item.state === stateFilter) && (!processFilter || item.process_key === processFilter))
  const counts = { all: workflows.length, progress: workflows.filter(item => ['submitted', 'under_review', 'reviewed'].includes(item.state)).length, escalated: workflows.filter(item => item.state === 'escalated').length, completed: workflows.filter(item => ['approved', 'executed', 'rejected'].includes(item.state)).length }
  const processOptions = [...new Map(workflows.map(item => [item.process_key, item.label])).entries()]
  return <div className="fade-in principal-operations workflow-page workflow-monitor-center"><div className="workflow-head"><div><p className="eyebrow">MONITORING CENTER</p><h1>Workflow Center</h1><p>Track requests through their approval lifecycle.</p></div><button className="btn btn-crimson" onClick={() => setShowStart(true)}>+ Initiate request</button></div><div className="workflow-summary">{[['All Workflows', counts.all], ['In Progress', counts.progress], ['Escalated', counts.escalated], ['Completed', counts.completed]].map(([label, value]) => <div className="workflow-stat" key={String(label)}><span>{label}</span><b>{value}</b></div>)}</div><div className="workflow-filters"><select className="select" value={processFilter} onChange={event => setProcessFilter(event.target.value)}><option value="">All processes</option>{processOptions.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><select className="select" value={stateFilter} onChange={event => setStateFilter(event.target.value)}><option value="">All states</option>{[...new Set(workflows.map(item => item.state))].map(state => <option key={state}>{state}</option>)}</select></div>{error && <div className="workflow-error">{error}<button className="btn btn-out" onClick={() => void load()}>Retry</button></div>}{loading ? <Spinner /> : <section className="card workflow-list-card"><div className="tbl-scroll">{filtered.length === 0 ? <Empty icon="◇" text="No workflows found for the selected filters." /> : <table className="tbl workflow-table"><thead><tr><th>Process</th><th>Request</th><th>Initiator</th><th>Current owner</th><th>Stage</th><th>State</th><th>Updated</th><th /></tr></thead><tbody>{filtered.map(item => <tr key={item.id}><td><b>{item.label}</b></td><td className="workflow-title">{item.title}</td><td>{item.initiator}</td><td>{item.current_owner || item.chain?.[item.current_stage] || 'Not assigned'}</td><td className="mono">{Number(item.current_stage || 0) + 1}/{item.chain?.length || 0}</td><td><StatePill s={item.state} /></td><td>{item.updated_at ? new Date(item.updated_at).toLocaleDateString() : 'Not available'}</td><td><button className="btn btn-out" onClick={() => setSelected(item)}>Open</button></td></tr>)}</tbody></table>}</div></section>}{showStart && <PrincipalWorkflowStart onClose={() => setShowStart(false)} onDone={() => { setShowStart(false); void load(); onChange() }} />}{selected && <PrincipalApprovalDetail wf={selected} onClose={() => setSelected(null)} onDone={() => { setSelected(null); void load(); onChange() }} />}</div>
}

function PrincipalWorkflowStart({ onClose, onDone }: any) {
  const [processes, setProcesses] = useState<any[]>([]), [key, setKey] = useState(''), [title, setTitle] = useState(''), [amount, setAmount] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('')
  useEffect(() => { api.processes().then(response => { setProcesses(response.processes || []); setKey(response.processes?.[0]?.key || '') }).catch(() => setError('Unable to load workflow processes.')) }, [])
  const process = processes.find(item => item.key === key)
  const submit = async () => { if (!title.trim()) { setError('Describe the request.'); return }; setBusy(true); setError(''); try { await api.startWorkflow(key, title, process?.amount && amount ? Number(amount) : undefined); onDone() } catch (e: any) { setError(e.message || 'Unable to submit workflow.'); setBusy(false) } }
  return <div className="modal-bg" onClick={onClose}><div className="modal workflow-start-modal" onClick={event => event.stopPropagation()}><div className="modal-h"><h3>Initiate a request</h3><button className="modal-x" onClick={onClose}>×</button></div><div className="modal-b">{error && <div className="workflow-error">{error}</div>}<label className="workflow-field">Process<select className="select" value={key} onChange={event => setKey(event.target.value)}>{processes.map(item => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label>{process && <div className="workflow-chain-preview">{process.chain.map((name: string, index: number) => <span key={`${name}-${index}`}>Stage {index}: <b>{name}</b></span>)}</div>}<label className="workflow-field">Request description<input className="inp" value={title} onChange={event => setTitle(event.target.value)} /></label>{process?.amount && <label className="workflow-field">Amount (INR)<input className="inp mono" value={amount} onChange={event => setAmount(event.target.value)} /></label>}</div><div className="modal-f"><button className="btn btn-out" onClick={onClose}>Cancel</button><button className="btn btn-crimson" onClick={() => void submit()} disabled={busy}>{busy ? 'Submitting...' : 'Submit request'}</button></div></div></div>
}